### ISSUE TITLE
zfs list -r does not snow snapshots

### ISSUE THREAD

**Issue by torriem** [zfs-linux/zfs#103]
On Solaris 10, zfs list -r <fsname> shows snapshots in the list of file systems.  On my RHEL6 box it does not show the snapshots at all.

**Comment by mitra** [comment]
Is the snapshot list displayed if you do

zfs list -t all ?

**Comment by mitra** [comment]
Is the snapshot list displayed if you do

zfs list -t all ?

**Comment by torriem** [comment]
Yes that works.  Further, zfs list -t all -r zfs/path works as well.  Perhaps the default behavior of the zfs command has changed between Solaris 10 and the latest OpenSolaris code that zfs on linux uses?

**Comment by torriem** [comment]
This issue should probably be closed; I was simply not aware of the new zfs list behavior since Solaris 10 release 6.
