### ISSUE TITLE
Dbench hangs and causes the driver to spew error messages

### ISSUE THREAD

**Issue by ccope** [zfs-linux/zfs#109]
When running dbench 4.00 through the Phoronix Testing Suite "disk" test suite, installed from the Ubuntu repositories, dbench will lock up during the first run, and the following messages appear in dmesg.

Running on Ubuntu 10.04 LTS x86_64 on a Terremark VMware-based virtual machine. Using kernel package "linux-image-virtual-lts-backport-maverick". I'm using the package from the main kqstor site (I had to move the modules to the appropriate directory since it was the virtual, not server kernel). There is a single zfs filesystem mounted at /mypool/demo, on a zpool consisting of a 50gb partition. /home is symlinked to /mypool/demo so that the benchmarking suite would conduct tests on the correct partition.
uname -a:
Linux ubuntu 2.6.35-22-virtual #34~lucid1-Ubuntu SMP Mon Oct 11 15:07:52 UTC 2010 x86_64 GNU/Linux

<pre>
Jan 25 11:19:46 zfs-test kernel: [   10.481654] SPL: Loaded Solaris Porting Layer v0.5.2
Jan 25 11:19:46 zfs-test kernel: [   10.615186] zunicode: module license 'CDDL' taints kernel.
Jan 25 11:19:46 zfs-test kernel: [   10.615191] Disabling lock debugging due to kernel taint
Jan 25 11:19:47 zfs-test kernel: [   11.354596] ZFS: Loaded ZFS Filesystem v0.5.1
Jan 25 11:19:47 zfs-test kernel: [   11.643856] checking : this : super_block magic no : 2fc12fc1
Jan 25 11:19:47 zfs-test kernel: [   11.736484] checking : this : super_block magic no : 2fc12fc1
Jan 25 17:37:29 zfs-test kernel: [22673.770588] CPU 3
Jan 25 17:37:29 zfs-test kernel: [22673.770623] Modules linked in: lzfs zfs(P) zcommon(P) znvpair(P) zavl(P) zlib_deflate zunicode(P) spl acpiphp ppdev parport_pc psmouse intel_agp lp shpchp i2c_piix4 serio_raw parport vmware_balloon vmw_pvscsi floppy mptspi mptscsih mptbase vmxnet3
Jan 25 17:37:29 zfs-test kernel: [22673.771066]
Jan 25 17:37:29 zfs-test kernel: [22673.771094] Pid: 2086, comm: dbench Tainted: P            2.6.35-22-virtual #34~lucid1-Ubuntu 440BX Desktop Reference Platform/VMware Virtual Platform
Jan 25 17:37:29 zfs-test kernel: [22673.771327] RIP: 0010:[<ffffffffa00d2e78>]  [<ffffffffa00d2e78>] tsd_hash_search+0x98/0xe0 [spl]
Jan 25 17:37:29 zfs-test kernel: [22673.771532] RSP: 0018:ffff880134385df8  EFLAGS: 00010286
Jan 25 17:37:29 zfs-test kernel: [22673.771624] RAX: dead000000100100 RBX: ffff88012b0a9de0 RCX: 0000000000000037
Jan 25 17:37:29 zfs-test kernel: [22673.771747] RDX: dead000000100100 RSI: 1300000000000000 RDI: ffff88013b06cf10
Jan 25 17:37:29 zfs-test kernel: [22673.771870] RBP: ffff880134385e18 R08: ffffffffbed0104c R09: 00007f07763df5c0
Jan 25 17:37:29 zfs-test kernel: [22673.771993] R10: 0000000000002a33 R11: 0000000000000246 R12: ffff88013b06cf10
Jan 25 17:37:29 zfs-test kernel: [22673.772116] R13: 0000000000000002 R14: 0000000000000826 R15: ffff88013b0454c0
Jan 25 17:37:29 zfs-test kernel: [22673.772241] FS:  00007f0776a46700(0000) GS:ffff880001f80000(0000) knlGS:0000000000000000
Jan 25 17:37:29 zfs-test kernel: [22673.772381] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 25 17:37:29 zfs-test kernel: [22673.772605] CR2: 00007f0776a52000 CR3: 000000010d7a7000 CR4: 00000000000006e0
Jan 25 17:37:29 zfs-test kernel: [22673.773561] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Jan 25 17:37:29 zfs-test kernel: [22673.773811] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
Jan 25 17:37:29 zfs-test kernel: [22673.774080] Process dbench (pid: 2086, threadinfo ffff880134384000, task ffff880125c42dc0)
Jan 25 17:37:29 zfs-test kernel: [22673.774673]  0000000000000002 0000000000000004 0000000000000826 00007fff146db158
Jan 25 17:37:29 zfs-test kernel: [22673.774969] <0> ffff880134385e78 ffffffffa00d34b5 ffff880134385ee8 ffff8800b47c2b80
Jan 25 17:37:29 zfs-test kernel: [22673.775391] <0> ffff880134385ed8 0000000000000000 ffff880134385e78 ffff8801211e9000
Jan 25 17:37:29 zfs-test kernel: [22673.776128]  [<ffffffffa00d34b5>] tsd_set+0x75/0x360 [spl]
Jan 25 17:37:29 zfs-test kernel: [22673.776592]  [<ffffffffa0208633>] zfs_fsync+0x33/0xe0 [zfs]
Jan 25 17:37:29 zfs-test kernel: [22673.776844]  [<ffffffffa02a86e1>] lzfs_vnop_fsync+0x61/0x110 [lzfs]
Jan 25 17:37:29 zfs-test kernel: [22673.777120]  [<ffffffff8117a66c>] vfs_fsync_range+0x7c/0xa0
Jan 25 17:37:29 zfs-test kernel: [22673.777359]  [<ffffffff8117a6fc>] vfs_fsync+0x1c/0x20
Jan 25 17:37:29 zfs-test kernel: [22673.777587]  [<ffffffff8117a73a>] do_fsync+0x3a/0x60
Jan 25 17:37:29 zfs-test kernel: [22673.777813]  [<ffffffff8117a790>] sys_fsync+0x10/0x20
Jan 25 17:37:29 zfs-test kernel: [22673.778059]  [<ffffffff8100a0f2>] system_call_fastpath+0x16/0x1b
Jan 25 17:37:29 zfs-test kernel: [22673.779503]  RSP <ffff880134385df8>
Jan 25 17:37:29 zfs-test kernel: [22673.780340] ---[ end trace bdce8a560ce84c4f ]---
Jan 25 17:38:34 zfs-test kernel: [22738.632520] Modules linked in: lzfs zfs(P) zcommon(P) znvpair(P) zavl(P) zlib_deflate zunicode(P) spl acpiphp ppdev parport_pc psmouse intel_agp lp shpchp i2c_piix4 serio_raw parport vmware_balloon vmw_pvscsi floppy mptspi mptscsih mptbase vmxnet3
Jan 25 17:38:34 zfs-test kernel: [22738.632520] CPU 2
Jan 25 17:38:34 zfs-test kernel: [22738.632520] Modules linked in: lzfs zfs(P) zcommon(P) znvpair(P) zavl(P) zlib_deflate zunicode(P) spl acpiphp ppdev parport_pc psmouse intel_agp lp shpchp i2c_piix4 serio_raw parport vmware_balloon vmw_pvscsi floppy mptspi mptscsih mptbase vmxnet3
Jan 25 17:38:34 zfs-test kernel: [22738.632520]
Jan 25 17:38:34 zfs-test kernel: [22738.632520] Pid: 2088, comm: dbench Tainted: P      D     2.6.35-22-virtual #34~lucid1-Ubuntu 440BX Desktop Reference Platform/VMware Virtual Platform
Jan 25 17:38:34 zfs-test kernel: [22738.632520] RIP: 0010:[<ffffffff81036d42>]  [<ffffffff81036d42>] __ticket_spin_lock+0x12/0x20
Jan 25 17:38:34 zfs-test kernel: [22738.632520] RSP: 0018:ffff8801105b3dd8  EFLAGS: 00000297
Jan 25 17:38:34 zfs-test kernel: [22738.632520] RAX: 0000000000002b2a RBX: ffff8801105b3dd8 RCX: 0000000000000037
Jan 25 17:38:34 zfs-test kernel: [22738.632520] RDX: 78bfefafe3740828 RSI: 0a00000000000000 RDI: ffff88013b06cf10
Jan 25 17:38:34 zfs-test kernel: [22738.632520] RBP: ffffffff8100aa8e R08: ffffefafe3740828 R09: 00007f07763df5c0
Jan 25 17:38:34 zfs-test kernel: [22738.632520] R10: 0000000000002986 R11: 0000000000000246 R12: ffffc90013176a50
Jan 25 17:38:34 zfs-test kernel: [22738.632520] R13: ffff880100010010 R14: 0000000000000000 R15: ffff8801105b3dd8
Jan 25 17:38:34 zfs-test kernel: [22738.632520] FS:  00007f0776a46700(0000) GS:ffff880001f00000(0000) knlGS:0000000000000000
Jan 25 17:38:34 zfs-test kernel: [22738.632520] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 25 17:38:34 zfs-test kernel: [22738.632520] CR2: 00007f0776a52000 CR3: 0000000104716000 CR4: 00000000000006e0
Jan 25 17:38:34 zfs-test kernel: [22738.632520] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000

Jan 25 17:38:34 zfs-test kernel: [22738.632520] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
Jan 25 17:38:34 zfs-test kernel: [22738.632520] Process dbench (pid: 2088, threadinfo ffff8801105b2000, task ffff880125c416e0)
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  ffff8801105b3de8 ffffffff815a423e ffff8801105b3e18 ffffffffa00d2e5a
Jan 25 17:38:34 zfs-test kernel: [22738.632520] <0> 0000000000000002 0000000000000004 0000000000000828 00007fff146db158
Jan 25 17:38:34 zfs-test kernel: [22738.632520] <0> ffff8801105b3e78 ffffffffa00d34d8 ffff8801105b3ee8 ffff8800b47c2b80
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff815a423e>] ? _raw_spin_lock+0xe/0x20
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa00d2e5a>] ? tsd_hash_search+0x7a/0xe0 [spl]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa00d34d8>] ? tsd_set+0x98/0x360 [spl]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa0208633>] ? zfs_fsync+0x33/0xe0 [zfs]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa02a86e1>] ? lzfs_vnop_fsync+0x61/0x110 [lzfs]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a66c>] ? vfs_fsync_range+0x7c/0xa0
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a6fc>] ? vfs_fsync+0x1c/0x20
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a73a>] ? do_fsync+0x3a/0x60
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a790>] ? sys_fsync+0x10/0x20
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8100a0f2>] ? system_call_fastpath+0x16/0x1b
Jan 25 17:38:34 zfs-test kernel: [22738.632520] Call Trace:
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff815a423e>] ? _raw_spin_lock+0xe/0x20
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa00d2e5a>] ? tsd_hash_search+0x7a/0xe0 [spl]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa00d34d8>] ? tsd_set+0x98/0x360 [spl]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa0208633>] ? zfs_fsync+0x33/0xe0 [zfs]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffffa02a86e1>] ? lzfs_vnop_fsync+0x61/0x110 [lzfs]
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a66c>] ? vfs_fsync_range+0x7c/0xa0
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a6fc>] ? vfs_fsync+0x1c/0x20
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a73a>] ? do_fsync+0x3a/0x60
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8117a790>] ? sys_fsync+0x10/0x20
Jan 25 17:38:34 zfs-test kernel: [22738.632520]  [<ffffffff8100a0f2>] ? system_call_fastpath+0x16/0x1b
(many more similar looking errors follow)
</pre>

**Comment by nkhare** [comment]
We also ran dbench but on the real hardware and we did not the see any problem. 
We'll see if we can re-produce the problem.
How much RAM does your virtual machine have?

**Comment by ccope** [comment]
4GB
