### ISSUE TITLE
Setting the property casesensitivity to insensitive unable to touch the file

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#11]

**Comment by sandipd** [comment]
Updated by Harshada Sangale 14 days ago

Comment

[root@kqinfo module]# zfs create -o casesensitivity=insensitive tank/fs2
[root@kqinfo module]# touch /tank/fs2/a
touch: cannot touch `/tank/fs2/a': Unknown error 524

[root@kqinfo module]# zfs get casesensitivity tank/fs2
NAME PROPERTY VALUE SOURCE
tank/fs2 casesensitivity insensitive -

**Comment by mitra** [comment]
fixed
