### ISSUE TITLE
zpool history

### ISSUE THREAD

**Issue by joseangel** [zfs-linux/zfs#115]
<pre>
root@storsv2:~# zpool history
History for 'jbodpool':
2011-02-01.00:26:51 zpool create jbodpool sdb
2011-02-01.00:28:02 zfs create jbodpool/share

root@storsv2:~# tail -f /var/log/messages
[  617.532418] Pid: 1749, comm: zpool Tainted: P           2.6.32-28-server #55-Ubuntu
[  617.532421] Call Trace:
[  617.532436]  [<ffffffffa00e9a47>] spl_debug_dumpstack+0x27/0x40 [spl]
[  617.532444]  [<ffffffffa00ed81d>] kmem_alloc_debug+0x11d/0x130 [spl]
[  617.532482]  [<ffffffffa01f69ff>] zfs_ioc_pool_get_history+0x9f/0x110 [zfs]
[  617.532489]  [<ffffffffa0172d4e>] ? pool_namecheck+0x5e/0x180 [zcommon]
[  617.532517]  [<ffffffffa01f72ff>] zfsdev_ioctl+0xef/0x1c0 [zfs]
[  617.532523]  [<ffffffff81154472>] vfs_ioctl+0x22/0xa0
[  617.532527]  [<ffffffff81117cc3>] ? expand_downwards+0x83/0x1b0
[  617.532530]  [<ffffffff81154611>] do_vfs_ioctl+0x81/0x410
[  617.532535]  [<ffffffff8155e173>] ? do_page_fault+0x153/0x3b0
[  617.532538]  [<ffffffff81154a21>] sys_ioctl+0x81/0xa0
[  617.532542]  [<ffffffff810121b2>] system_call_fastpath+0x16/0x1b
[  620.312832] SPL: Showing stack for process 1749
[  620.312838] Pid: 1749, comm: zpool Tainted: P           2.6.32-28-server #55-Ubuntu
[  620.312840] Call Trace:
[  620.312856]  [<ffffffffa00e9a47>] spl_debug_dumpstack+0x27/0x40 [spl]
[  620.312864]  [<ffffffffa00ed81d>] kmem_alloc_debug+0x11d/0x130 [spl]
[  620.312906]  [<ffffffffa01f69ff>] zfs_ioc_pool_get_history+0x9f/0x110 [zfs]
[  620.312912]  [<ffffffffa0172d4e>] ? pool_namecheck+0x5e/0x180 [zcommon]
[  620.312940]  [<ffffffffa01f72ff>] zfsdev_ioctl+0xef/0x1c0 [zfs]
[  620.312946]  [<ffffffff81154472>] vfs_ioctl+0x22/0xa0
[  620.312950]  [<ffffffff81117cc3>] ? expand_downwards+0x83/0x1b0
[  620.312954]  [<ffffffff81154611>] do_vfs_ioctl+0x81/0x410
[  620.312958]  [<ffffffff8155e173>] ? do_page_fault+0x153/0x3b0
[  620.312961]  [<ffffffff81154a21>] sys_ioctl+0x81/0xa0
[  620.312966]  [<ffffffff810121b2>] system_call_fastpath+0x16/0x1b
[  620.313004] SPL: Showing stack for process 1749
[  620.313007] Pid: 1749, comm: zpool Tainted: P           2.6.32-28-server #55-Ubuntu
[  620.313009] Call Trace:
[  620.313016]  [<ffffffffa00e9a47>] spl_debug_dumpstack+0x27/0x40 [spl]
[  620.313023]  [<ffffffffa00ed81d>] kmem_alloc_debug+0x11d/0x130 [spl]
[  620.313051]  [<ffffffffa01f69ff>] zfs_ioc_pool_get_history+0x9f/0x110 [zfs]
[  620.313056]  [<ffffffffa0172d4e>] ? pool_namecheck+0x5e/0x180 [zcommon]
[  620.313083]  [<ffffffffa01f72ff>] zfsdev_ioctl+0xef/0x1c0 [zfs]
[  620.313086]  [<ffffffff81154472>] vfs_ioctl+0x22/0xa0
[  620.313089]  [<ffffffff81117cc3>] ? expand_downwards+0x83/0x1b0
[  620.313092]  [<ffffffff81154611>] do_vfs_ioctl+0x81/0x410
[  620.313096]  [<ffffffff8155e173>] ? do_page_fault+0x153/0x3b0
[  620.313099]  [<ffffffff81154a21>] sys_ioctl+0x81/0xa0
[  620.313102]  [<ffffffff810121b2>] system_call_fastpath+0x16/0x1b
root@storsv2:~#
root@storsv2:~# uname -a
Linux storsv2 2.6.32-28-server #55-Ubuntu SMP Mon Jan 10 23:57:16 UTC 2011 x86_64 GNU/Linux

</pre>

**Comment by mitra** [comment]
This is a warning for a large allocation. This does not affect the functionality. This will be fixed in the next release.

**Comment by joseangel** [comment]
Ok.

Congratulations for your work.
