### ISSUE TITLE
unknown type name 'vfs_t' 

### ISSUE THREAD

**Issue by ghost** [zfs-linux/zfs#119]
Hello,
i am c ompiling zfs on a gentoo 2.6.37 kernel
gcc 4.4.5

and run into this:
/home/lerouxp/zfs/zfs/include/sys/zfs_vfsops.h:47:2: error: unknown type name 'vfs_t'
/home/lerouxp/zfs/zfs/include/sys/zfs_znode.h:317:21: error: unknown type name 'vfs_t'

i googled for vfs_t, searched the source in zfs, and cannot find any where for a declaration of vfs_t

oddly though, a couple of weeks ago when i first tried to compile, i had no problems
i tried reverting to a previous tag, but with no success

any ideas?

sincerely

Philippe

**Comment by blind-oracle** [comment]
use 2.6.35

**Comment by blind-oracle** [comment]
well, under current git version it builds fine over 2.6.37.1

**Comment by ghost** [comment]
after git pull i'm now getting

zfs/zfs/module/zfs/../../module/zfs/zfs_vfsops.c: In function 'zfsvfs_teardown':
zfs/zfs/module/zfs/../../module/zfs/zfs_vfsops.c:1083:3: error: implicit declaration of function 'invalidate_inodes'

kernel :2.6.37-gentoo

dont' have time to update kernel now, and will be gone for a month. so i'll check in latter

many thanks

**Comment by blind-oracle** [comment]
i have gentoo and vanilla 2.6.37.1, it builds fine but for lzfs, where you need to remove -Werror to build it from Makefiles.

**Comment by ghost** [comment]
just got back home!

git pull, configure; make; make install; modprobe;...

and it works! same kernel 2.6.37-gentoo (i had also updated all the system though i dont think that made a difference)

oh but wait 2.6.68 made it to gentoo... let me try!

many thanks for all the developments

**Comment by blind-oracle** [comment]
Just dont use it with sensitive data :) BTW, the original zfs port by Behlendorf (https://github.com/behlendorf) now supports zfs posix layer, so it's worth a try, but a couple of weeks ago when i tried it, the speed was horrible (about 10mb/s)
