### ISSUE TITLE
kernel panic while creating more than 1000000 hardlinks 

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#13]
when running a script to create number of hardlinks
It works till the count is near about 10,00,000 hardlinks after that it ooped.

plz see screen shot for oops msg

How to run the script.
1) $ ./symlink.sh -s/-h number of links ( -s for symlink and -h for hardlink )

2) When you want run script next time, remove the "temp_directory"

changeset: 143:82d881b28e24
tag: tip
parent: 142:8410057f8ba7
parent: 141:78c080ac1574
user: Prasad Joshi prasad@kqinfotech.com
date: Mon Sep 20 21:45:55 2010 +0530
summary: Merged the changes.

**Comment by sandipd** [comment]
Updated by Prasad Joshi 20 days ago

```
* Assigned to set to sandip divekar
```

Comment

Please put the kernel panic message in the bug report.
#2
Updated by Prasad Joshi 18 days ago

```
* Assigned to changed from sandip divekar to Prasad Joshi
```

Comment

I checked with the ext2/3/4 file systems it allows only 64999 hardlinks. We might need to put a limit on number of hardlinks to each file.

zfs_getattr() function fills information about a file in a struct vattr.

typedef struct vattr {
....
short va_nlink; /\* # links */
....
} vattr_t;

As the variable maintaining the link count is signed short, I guess the limit should be 2^15 - 1 = 32767.

Here is an interesting screenshot taken during more than 5 Lakh links were created

[root@localhost scripts]# date; stat /tank/file
Sat Sep 25 18:34:42 IST 2010
  File: `/tank/file'
  Size: 0           Blocks: 1          IO Block: 512    regular empty file
Device: 0h/0d   Inode: 19          Links: 4294967121
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2010-09-25 18:05:45.481704309 +0530
Modify: 2010-09-25 18:05:45.481704309 +0530
Change: 2010-09-25 18:34:42.586129000 +0530

[root@localhost scripts]# date; stat /tank/file
Sat Sep 25 18:34:43 IST 2010
  File: `/tank/file'
  Size: 0           Blocks: 1          IO Block: 512    regular empty file
Device: 0h/0d   Inode: 19          Links: 115
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2010-09-25 18:05:45.481704309 +0530
Modify: 2010-09-25 18:05:45.481704309 +0530
Change: 2010-09-25 18:34:43.565934000 +0530

[root@localhost scripts]# date; stat /tank/file
Sat Sep 25 18:36:03 IST 2010
  File: `/tank/file'
  Size: 0           Blocks: 1          IO Block: 512    regular empty file
Device: 0h/0d   Inode: 19          Links: 32285
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2010-09-25 18:05:45.481704309 +0530
Modify: 2010-09-25 18:05:45.481704309 +0530
Change: 2010-09-25 18:36:03.114470000 +0530

[root@localhost scripts]# date; stat /tank/file
Sat Sep 25 18:36:04 IST 2010
  File: `/tank/file'
  Size: 0           Blocks: 1          IO Block: 512    regular empty file
Device: 0h/0d   Inode: 19          Links: 32684
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2010-09-25 18:05:45.481704309 +0530
Modify: 2010-09-25 18:05:45.481704309 +0530
Change: 2010-09-25 18:36:04.015606000 +0530

[root@localhost scripts]# date; stat /tank/file
Sat Sep 25 18:36:04 IST 2010
  File: `/tank/file'
  Size: 0           Blocks: 1          IO Block: 512    regular empty file
Device: 0h/0d   Inode: 19          Links: 4294934864
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2010-09-25 18:05:45.481704309 +0530
Modify: 2010-09-25 18:05:45.481704309 +0530
Change: 2010-09-25 18:36:04.913578000 +0530

stat command results in getattr call to a file system. Linux kernel uses struct kstat to get the file attributes from a file system.
struct kstat {
....
unsigned long nlinks;
....
};
Hence we see numbers like 4294967121 in stat output.
#3
Updated by Anand Mitra 14 days ago

```
* Assigned to changed from Prasad Joshi to Anand Mitra
```

Comment
- changes done.
- assigning to mitra for review.

**Comment by mitra** [comment]
this has been fixed, we dont allow more than UINT32_MAX hardlinks now
