### ISSUE TITLE
Assertion failure in dnode_sync.c:464:dnode_sync_free()

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#15]
Hardware Information
[root@localhost ~]# uname -a
Linux localhost.localdomain 2.6.31.5-127.fc12.x86_64 #1 SMP Sat Nov 7 21:11:14 EST 2009 x86_64 x86_64 x86_64 GNU/Linux

OS: Fedora 12

HG Repository Version:
[anurag@localhost ZFS_kq]$ hg heads
changeset: 143:82d881b28e24
tag: tip
parent: 141:8410057f8ba7
parent: 142:78c080ac1574
user: Prasad Joshi prasad@kqinfotech.com
date: Mon Sep 20 21:45:55 2010 +0530
summary: Merged the changes.

Steps
1. Create a ZPOOL.
2. Keep on running wrv in loop.

Details

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:SPLError: 5754:1904:(dnode_sync.c:464:dnode_sync_free()) VERIFY3((((dn->dn_phys)->dn_flags & (1<<0)) ? (dn->dn_phys)->dn_used : (dn->dn_phys)->dn_used << 9) == 0) failed (2048 == 0)

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:SPLError: 5754:1968:(dnode_sync.c:464:dnode_sync_free()) SBUG

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:------------[ cut here ]------------

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:invalid opcode: 0000 [#1] SMP 

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:last sysfs file: /sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/charge_full

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:Stack:

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:Call Trace:

Message from syslogd@localhost at Sep 22 17:53:21 ...
 kernel:Code: e0 83 3d e1 47 02 00 00 74 0a c7 05 55 94 02 00 01 00 00 00 31 ff e8 06 ec ff ff 89 df e8 7d fe ff ff 83 3d c0 47 02 00 00 74 04 <0f> 0b eb fe 65 48 8b 14 25 90 c6 00 00 b8 02 00 00 00 48 87 02 

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:SPLError: 28494:920:(dmu_tx.c:1029:dmu_tx_assign()) ASSERTION(!dsl_pool_sync_context(tx->tx_pool)) failed

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:SPLError: 28494:984:(dmu_tx.c:1029:dmu_tx_assign()) SBUG

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:------------[ cut here ]------------

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:invalid opcode: 0000 [#2] SMP 

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:last sysfs file: /sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/charge_full

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:Stack:

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:Call Trace:

Message from syslogd@localhost at Sep 22 17:53:22 ...
 kernel:Code: e0 83 3d e1 47 02 00 00 74 0a c7 05 55 94 02 00 01 00 00 00 31 ff e8 06 ec ff ff 89 df e8 7d fe ff ff 83 3d c0 47 02 00 00 74 04 <0f> 0b eb fe 65 48 8b 14 25 90 c6 00 00 b8 02 00 00 00 48 87 02 

Sep 22 17:53:22 localhost kernel: ------------[ cut here ]------------
Sep 22 17:53:22 localhost kernel: kernel BUG at /home/anurag/ZFS_kq/spl-0.4.7/module/spl/spl-debug.c:1129!
Sep 22 17:53:22 localhost kernel: invalid opcode: 0000 [#2] SMP
Sep 22 17:53:22 localhost kernel: last sysfs file: /sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/charge_full
Sep 22 17:53:22 localhost kernel: CPU 1
Sep 22 17:53:22 localhost kernel: Modules linked in: nfsd lockd nfs_acl auth_rpcgss exportfs usb_storage lzfs zfs(P) zcommon(P) zunicode(P) znvpair(P) zavl(P) spl zlib_deflate nls_utf8 fuse rfcomm sco bridge stp llc bnep l2cap vboxnetadp vboxnetflt vboxdrv sunrpc ipv6 cpufreq_ondemand acpi_cpufreq freq_table dm_multipath uinput snd_hda_codec_idt snd_hda_codec_intelhdmi snd_hda_intel snd_hda_codec b43 snd_hwdep snd_seq mac80211 snd_seq_device snd_pcm uvcvideo snd_timer btusb firewire_ohci cfg80211 bluetooth dell_laptop videodev snd sdhci_pci firewire_core sdhci dcdbas ssb mmc_core sky2 v4l1_compat iTCO_wdt crc_itu_t soundcore ricoh_mmc v4l2_compat_ioctl32 rfkill iTCO_vendor_support snd_page_alloc i2c_i801 wmi serio_raw joydev i915 drm_kms_helper drm i2c_algo_bit i2c_core video output [last unloaded: microcode]
Sep 22 17:53:22 localhost kernel: Pid: 28494, comm: wrv.fs Tainted: P      D    2.6.31.5-127.fc12.x86_64 #1 Inspiron 1525
Sep 22 17:53:22 localhost kernel: RIP: 0010:[<ffffffffa0541d82>]  [<ffffffffa0541d82>] spl_debug_bug+0x9c/0xb8 [spl]
Sep 22 17:53:22 localhost kernel: RSP: 0018:ffff880000df7c38  EFLAGS: 00010202
Sep 22 17:53:22 localhost kernel: RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffff880000df7bf0
Sep 22 17:53:22 localhost kernel: RDX: 0000000000000000 RSI: 0000000000000202 RDI: 0000000000000202
Sep 22 17:53:22 localhost kernel: RBP: ffff880000df7c68 R08: ffff880000df7bf0 R09: 0000000000000000
Sep 22 17:53:22 localhost kernel: R10: ffff88007c966020 R11: ffff880000965b00 R12: ffff880000df7e88
Sep 22 17:53:22 localhost kernel: R13: 0000000000000200 R14: 0000000000000000 R15: ffff880049031000
Sep 22 17:53:22 localhost kernel: FS:  00007f15ba81c710(0000) GS:ffff8800019dc000(0000) knlGS:0000000000000000
Sep 22 17:53:22 localhost kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
Sep 22 17:53:22 localhost kernel: CR2: 00007f1572bfcff8 CR3: 000000002307e000 CR4: 00000000000406e0
Sep 22 17:53:22 localhost kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Sep 22 17:53:22 localhost kernel: DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
Sep 22 17:53:22 localhost kernel: Process wrv.fs (pid: 28494, threadinfo ffff880000df6000, task ffff8800369ede00)
Sep 22 17:53:22 localhost kernel: Stack:
Sep 22 17:53:22 localhost kernel: 0000000000000000 0000000000000000 ffffffffa055727c 0000000000000200
Sep 22 17:53:22 localhost kernel: <0> 0000000000000000 ffff880055670000 ffff880000df7d38 ffffffffa05fe519
Sep 22 17:53:22 localhost kernel: <0> 0000000000000000 0000000000000000 ffffffffa0689353 ffffc900178f9800
Sep 22 17:53:22 localhost kernel: Call Trace:
Sep 22 17:53:22 localhost kernel: [<ffffffffa05fe519>] dmu_tx_assign+0x14c/0x632 [zfs]
Sep 22 17:53:22 localhost kernel: [<ffffffffa0616183>] ? dsl_dataset_block_freeable+0x16/0x23 [zfs]
Sep 22 17:53:22 localhost kernel: [<ffffffffa05ff0a1>] ? dmu_tx_count_dnode+0x5e/0x89 [zfs]
Sep 22 17:53:22 localhost kernel: [<ffffffffa05ffd06>] ? dmu_tx_hold_write+0x195/0x1a2 [zfs]
Sep 22 17:53:22 localhost kernel: [<ffffffffa05ff16b>] ? dmu_tx_hold_bonus+0x9f/0xa8 [zfs]
Sep 22 17:53:22 localhost kernel: [<ffffffffa0669597>] zfs_write+0x4c2/0x8d5 [zfs]
Sep 22 17:53:22 localhost kernel: [<ffffffffa06ee817>] lzfs_vnop_write+0x2f4/0x3fb [lzfs]
Sep 22 17:53:22 localhost kernel: [<ffffffff810fc922>] vfs_write+0xae/0x10b
Sep 22 17:53:22 localhost kernel: [<ffffffff810fca3f>] sys_write+0x4a/0x6e
Sep 22 17:53:22 localhost kernel: [<ffffffff81011cf2>] system_call_fastpath+0x16/0x1b
Sep 22 17:53:22 localhost kernel: Code: e0 83 3d e1 47 02 00 00 74 0a c7 05 55 94 02 00 01 00 00 00 31 ff e8 06 ec ff ff 89 df e8 7d fe ff ff 83 3d c0 47 02 00 00 74 04 <0f> 0b eb fe 65 48 8b 14 25 90 c6 00 00 b8 02 00 00 00 48 87 02
Sep 22 17:53:22 localhost kernel: RIP  [<ffffffffa0541d82>] spl_debug_bug+0x9c/0xb8 [spl]
Sep 22 17:53:22 localhost kernel: RSP <ffff880000df7c38>
Sep 22 17:53:22 localhost kernel: ---[ end trace 5532fdd3ac8a3cf1 ]---

**Comment by sandipd** [comment]
Updated by Anand Mitra 14 days ago

Comment

how long did this run before hitting the assert ?
#2
Updated by Prasad Joshi 14 days ago

Comment

the bug is not easily reproducible. Some times assert hit in 15 mins other times it may take hours. But, I was able to reproduce this several times.

**Comment by mitra** [comment]
wrv runs over night with out hitting this problem.
