### ISSUE TITLE
after snapshot creation and automounting the pool does not get destroyed

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#16]
1.zpool create tank dev
2. cp -r /usr/inlcude /tank
3. zfs snapshot tank@snap1
4. cd /tank/.zfs/snaphot/snap1
5. umount /tank/.zfs/snaphot/snap1
6, zfs destroy tank@snap1
7. umount /tank
8. zpool destroy tank -> pool busy

**Comment by prasad-joshi** [comment]
Exact steps to reproduce the problem
1. Create pool
2. Create a snapshot
3. Mount the snapshot by doing CD into the snapshot directory
4. Umount the snapshot
5. Destroy the snapshot
6. Umount the pool
7. Try to destroy the pool and it returns pool BUSY

**Comment by prasad-joshi** [comment]
# Explaination of what is happening

Every time user uses the path of snapshot the reference count on SPA is incremented. IMHO, every time the snapshot directory path is used, code mounting the snapshot is invoked. It automatically increments the reference count. It can be proved with the following screen shot.

[root@localhost snap1]# dmesg | tail -n 1
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost snap1]# dmesg | tail -n 2
SPLError: 1645:2200:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=204 spa_minref=8
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost snap1]# cd -
/home/prasad
[root@localhost ~]# dmesg | tail -n 2
SPLError: 1645:2200:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=204 spa_minref=8
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost ~]# umount /tank/.zfs/snapshot/snap1
[root@localhost ~]# dmesg | tail -n 2
SPLError: 1645:2200:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=204 spa_minref=8
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost ~]# umount /tank/.zfs/snapshot/snap1
[root@localhost ~]# dmesg | tail -n 2
SPLError: 2682:2072:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=215 spa_minref=8
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost ~]# umount /tank/.zfs/snapshot/snap1
[root@localhost ~]# dmesg | tail -n 2
SPLError: 2685:2072:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=226 spa_minref=8
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost ~]# umount /tank/.zfs/snapshot/snap1
[root@localhost ~]# dmesg | tail -n 2
SPLError: 2688:2072:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=237 spa_minref=8
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost ~]# cat /proc/mounts | grep -i zfs
tank /tank zfs rw,relatime,atime,noxattr,suid,devices,setuid,exec 0 0
[root@localhost ~]# umount /tank/.zfs/snapshot/snap1
[root@localhost ~]# cat /proc/mounts | grep -i zfs
tank /tank zfs rw,relatime,atime,noxattr,suid,devices,setuid,exec 0 0
[root@localhost ~]# dmesg | tail -n 2
SPLError: 2693:2072:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=248 spa_minref=8
SELinux: initialized (dev zfs, type zfs), not configured for labeling
[root@localhost ~]# umount /tank/.zfs/snapshot/snap1
[root@localhost ~]# dmesg | tail -n 2
SPLError: 2698:2072:(spl-err.c:66:vcmn_err()) WARNING: spa_open_ref: spa=ffff88001c80f000, spa_refcount=259 spa_minref=8

# SELinux: initialized (dev zfs, type zfs), not configured for labeling

I am not sure, but seems like mounting the snapshot during CD is not a good option. How does Solaris ZFS makes snapshot accessible? Do they mount the snapshot every time the snapshot is accessed? If it is the case then every time user leaves the snapshot directory it should be automatically unmounted.

**Comment by mitra** [comment]
fixed
