### ISSUE TITLE
snapshot bug

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#17]
1. manually mount snapshot or eg ( /mnt)
2. do cd or ls to automatically mount snapshot.
3. snapshot is not mounted automatically.
4. then unmount snapshot on /mnt dir
5. do step 2 again then ASSERT is hiT

[root@localhost cmd]# mount
/dev/sdd1 on / type ext4 (rw)
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
devpts on /dev/pts type devpts (rw,gid=5,mode=620)
tmpfs on /dev/shm type tmpfs (rw)
none on /proc/sys/fs/binfmt_misc type binfmt_misc (rw)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw)
tank on /tank type zfs (rw)
tank@snap1 on /mnt type zfs (rw)
[root@localhost cmd]#
[root@localhost cmd]#
[root@localhost cmd]#
[root@localhost cmd]#
[root@localhost cmd]#
[root@localhost cmd]#
[root@localhost cmd]# umount /mnt
[root@localhost cmd]# ls /tank/.zfs/snapshot/snap1/

Message from syslogd@localhost at Sep 13 12:00:07 ...
kernel:SPLError: 2412:1080:(spl-condvar.c:95:__cv_wait()) ASSERTION failed

Message from syslogd@localhost at Sep 13 12:00:07 ...
kernel:SPLError: 2412:1144:(spl-condvar.c:95:__cv_wait()) SBUG

**Comment by sandipd** [comment]
Updated by Anand Mitra 14 days ago

Comment

this bug has been fixed please update with revision number in hg which fixed it and description of the fix and finally close this bug

**Comment by nkhare** [comment]
closing the bug as per previous comment.
