### ISSUE TITLE
send/receive operations hits assert 

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#18]
will put more info.

**Comment by sandipd** [comment]
Updated by Neependra Khare about 1 month ago

```
* Assigned to set to Neependra Khare
```

#2
Updated by Anand Mitra about 1 month ago

```
* Target version set to GA
```

**Comment by nkhare** [comment]
I think after fixing few snapshot issues we are not facing this issue now.
Should we close this one?

**Comment by nkhare** [comment]
closing this now.

**Comment by tushk2** [comment]
send / receive operations work properly.
i have tried upto 90 Gb data

**Comment by tushk2** [comment]
i have tried send / receive operations in two systems it works.
