### ISSUE TITLE
read / write  buffered io produces oops

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#19]
backtrace : -

Stack traceback for pid 565
0xffff88000e202f00 565 25487 1 0 R 0xffff88000e2033a8 *utility.fs
sp ip Function (args)
0xffff880003f33c48 0xffffffffa01e7a3a [spl]uiomove+0x136 (invalid, invalid, invalid, 0xffff880003f33e68)
kdb_bb: address 0x0000000000001000 not recognised
Using old style backtrace, unreliable with no arguments
sp ip Function (args)
0xffff880003f33c48 0xffffffffa01e7a3a [spl]uiomove+0x136
0xffff880003f33c80 0xffffffffa02747e8 [zfs]dmu_buf_hold_array+0x72
0xffff880003f33ce0 0xffffffffa0274add [zfs]dmu_read_uio+0xf2
0xffff880003f33d00 0xffffffffa02a8eb8 [zfs]rrw_enter+0x362
0xffff880003f33d60 0xffffffffa02ea652 [zfs]zfs_read+0x1f9
0xffff880003f33d70 0xffffffff810f90a4 __mem_cgroup_try_charge+0x4a
0xffff880003f33df0 0xffffffffa036fda2 [lzfs]lzfs_vnop_read+0x331
0xffff880003f33e10 0xffffffff810e10a2 page_add_new_anon_rmap+0x3f
0xffff880003f33f00 0xffffffff810fce22 vfs_read+0xab
0xffff880003f33f40 0xffffffff810fcf3f sys_read+0x4a

**Comment by sandipd** [comment]
Updated by Anand Mitra 14 days ago

Comment

this is fixed please close.

**Comment by shrirang** [comment]
early bug not seen any more
