### ISSUE TITLE
stf test failed functional/large_files

### ISSUE THREAD

**Issue by mitra** [zfs-linux/zfs#2]
oot@localhost large_files]# ./setup sdb1
/dev/.udev/names/sdb1
/dev/sdb1
07:09:22 SUCCESS: /bin/umount /demopool/zfs
07:09:22 SUCCESS: /bin/umount /demopool
07:09:22 SUCCESS: /sbin/zpool destroy -f demopool
07:09:22 SUCCESS: /bin/rm -rf /demopool
TESTPOOL = demopool
07:09:23 SUCCESS: /sbin/zpool create -f demopool sdb1
07:09:23 SUCCESS: /sbin/zfs create demopool/zfs
[root@localhost large_files]# ./large_files_001_pos 
07:09:30 ASSERTION: Write a file to the allowable ZFS fs size.
07:09:31 NOTE: Invoke 'largest_file' with /demopool/zfs/test_file
write completed successfully, test failed
07:09:31 Successfully created a file to the maximum allowable size.
[root@localhost large_files]# ls

**Comment by tushk2** [comment]
In Solaris we have MAXOFFSET_T varible but problem is that in linux we dont have any declarations of MAXOFFSET_T.
In our script we create a new file. after that we lseek upto MAXOFFSET_T - 1 then it caught a signal SIGXFSZ for file is to large.
