### ISSUE TITLE
Rename the volume not working says dataset is busy

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#20]
[root@localhost kqinfo]# zpool list
NAME SIZE USED AVAIL CAP HEALTH ALTROOT
mypool 1.98G 74K 1.98G 0% ONLINE -

[root@localhost kqinfo]# zfs create -V 1024m mypool/vol
[root@localhost kqinfo]# ls /dev/mypool/
vol

[root@localhost kqinfo]# zfs rename mypool/vol mypool/vol1
cannot rename 'mypool/vol': dataset is busy
cannot create device links for 'mypool/vol': dataset is busy

**Comment by sandipd** [comment]
Updated by Anand Mitra about 1 month ago

```
* Target version set to GA
```

**Comment by nkhare** [comment]
Not seen in merged code. Closing it.
