### ISSUE TITLE
Bug occuring while creating zpool on ubuntu 10.4 ...

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#21]
steps

Found By : Vikram Jadhav vikram@kqinfotech.com

Subject : Bug

Hardware Information : AMD64

Software Information :

LINUX : ubuntu 10.4  ( 64 bit )

KERNEL VERSION : 2.6.32-24-server

DATE : 6 Sup 2010

STEPS:----->

1) Clone ZFS Source code
$] hg clone ssh://hg@bugs.kqinfotech.com///home/hg/ZFS_kq

2) Installing required packages

i) sudo apt-get install linux-headers-2.6.32-24-server

ii) sudo apt-get install zlibg-dev

iii) sudo apt-get install libssl-dev

iv) sudo apt-get install uuid-dev

3) Compilation

i) $] cd ZFS_kq/spl-0.4.7/

ii) $] ./configure --with-linux=/lib/modules/2.6.32-24-server    

iii) $] make    ----> Compile spl-0.4.7

iv) $] cd ..

v) $] cd zfs-0.4.7/

vi) $] ./configure --with-spl=/home/kqinfo/ZFS_kq/spl-0.4.7 --with-linux=/lib/modules/2.6.32-24-server/build

vii) $] make  ----> Compile zfs-0.4.7

4)
i) $] cp ZFS_kq/zfs-0.4.7/module/Module.symvers ZFS_kq/spl-0.4.7/module/

ii) make

5) Loading Module

i) ZFS_kq/zfs-0.4.7/script $] ./zfs.sh  ---> Inserting modules

6) Creating zpool :

i) ZFS_kq/zfs-0.4.7/cmd/zpool $] ./zpool list

**********_ERROR/Bug**_***********************:

Unable to open /dev/zfs: (21) Is a directory
internal error: failed to initialise ZFS library

7) Temparary Solution :

i)   Remove directory /dev/zfs

ii)  Unload Modules (./zfs.sh -u)

iii) Reload modules (./zfs.sh -v)

iv)  Create pool and so on.

Add

**Comment by sandipd** [comment]
Updated by Anand Mitra about 1 month ago

```
* Assigned to set to Harshada Sangale
* Target version set to beta
```

#2
Updated by Anand Mitra about 1 month ago

```
* Assigned to changed from Harshada Sangale to sandip divekar
```

**Comment by mitra** [comment]
this has been fixed.

**Comment by nkhare** [comment]
I haven't seen this problem after doing the merger. There were few changes in Brian's code which might be fixing this.https://github.com/behlendorf/zfs/commit/325f023544bbec6a478882c442e15304ee379759

Closing it for now.
