### ISSUE TITLE
disable allow and unallow commands as they are not supported

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#23]
user@user:~# zfs
missing command
usage: zfs command args ...
where 'command' is one of the following:

create [-p] [-o property=value] ... &lt;filesystem&gt;
        create [-ps] [-b blocksize] [-o property=value] ... -V &lt;size&gt; &lt;volume&gt;
        destroy [-rRf] &lt;filesystem|volume&gt;
        destroy [-rRd] &lt;snapshot&gt;

snapshot [-r] [-o property=value] ... &lt;filesystem@snapname|volume@snapname&gt;
        rollback [-rRf] &lt;snapshot&gt;
        clone [-p] [-o property=value] ... &lt;snapshot&gt; &lt;filesystem|volume&gt;
        promote &lt;clone-filesystem&gt;
        rename &lt;filesystem|volume|snapshot&gt; &lt;filesystem|volume|snapshot&gt;
        rename -p &lt;filesystem|volume&gt; &lt;filesystem|volume&gt;
        rename -r &lt;snapshot&gt; &lt;snapshot&gt;
        list [-rH][-d max] [-o property[,...]] [-t type[,...]] [-s property] ...
            [-S property] ... [filesystem|volume|snapshot] ...

set &lt;property=value&gt; &lt;filesystem|volume|snapshot&gt; ...
        get [-rHp] [-d max] [-o "all" | field[,...]] [-s source[,...]]
            <"all" | property[,...]> [filesystem|volume|snapshot] ...
        inherit [-rS] &lt;property&gt; &lt;filesystem|volume|snapshot&gt; ...
        upgrade [-v]
        upgrade [-r] [-V version] <-a | filesystem ...>
        userspace [-hniHp] [-o field[,...]] [-sS field] ... [-t type[,...]]
            &lt;filesystem|snapshot&gt;
        groupspace [-hniHpU] [-o field[,...]] [-sS field] ... [-t type[,...]]
            &lt;filesystem|snapshot&gt;

mount
        mount [-vO] [-o opts] <-a | filesystem>
        unmount [-f] <-a | filesystem|mountpoint>
        share <-a | filesystem>
        unshare <-a | filesystem|mountpoint>

send [-RDp] [-[iI] snapshot] &lt;snapshot&gt;
        receive [-vnF] &lt;filesystem|volume|snapshot&gt;
        receive [-vnF] -d &lt;filesystem&gt;

allow &lt;filesystem|volume&gt;
        allow [-ldug] <"everyone"|user|group>[,...] &lt;perm|@setname&gt;[,...]
            &lt;filesystem|volume&gt;
        allow [-ld] -e &lt;perm|@setname&gt;[,...] &lt;filesystem|volume&gt;
        allow -c &lt;perm|@setname&gt;[,...] &lt;filesystem|volume&gt;
        allow -s @setname &lt;perm|@setname&gt;[,...] &lt;filesystem|volume&gt;

unallow [-rldug] <"everyone"|user|group>[,...]
            [&lt;perm|@setname&gt;[,...]] &lt;filesystem|volume&gt;
        unallow [-rld] -e [&lt;perm|@setname&gt;[,...]] &lt;filesystem|volume&gt;
        unallow [-r] -c [&lt;perm|@setname&gt;[,...]] &lt;filesystem|volume&gt;
        unallow [-r] -s @setname [&lt;perm|@setname&gt;[,...]] &lt;filesystem|volume&gt;

hold [-r] &lt;tag&gt; &lt;snapshot&gt; ...
        holds [-r] &lt;snapshot&gt; ...
        release [-r] &lt;tag&gt; &lt;snapshot&gt; ...

Each dataset is of the form: pool/[dataset/]*dataset[@name]

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow

Need to disable the commands allow and unallow as they are not supported.

**Comment by mitra** [comment]
commands have been modified to notify that this operations is not supported
