### ISSUE TITLE
zfs promote deadlock

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#25]
1. zpool create tank dev1
2. cp -r /usr/include/ /tank
3. zfs snapshot tank@snap1
4. zfs clone tank@snap1 tank/clonefs
5. zfs promote tank/clonefs

tack traceback for pid 24746
0xffff88001c7a0000 24746 1265 0 0 D 0xffff88001c7a04a8 lt-zfs
sp ip Function (args)
0xffff88000bac5a88 0xffffffff814368af thread_return
0xffff88000bac5b60 0xffffffff81437e5c __down_write_nested+0x93 (invalid)
0xffff88000bac5ba0 0xffffffff81437e7f __down_write+0xb
0xffff88000bac5bb0 0xffffffff81437580 down_write+0x2f (0xffff8800149e0d20)
0xffff88000bac5bd0 0xffffffffa02a37cc [zfs]dsl_dataset_make_exclusive+0x9d (invalid, invalid)
0xffff88000bac5c20 0xffffffffa02ab372 [zfs]snaplist_make+0x142 (0xffff88000674f800, invalid, invalid, invalid, 0xffff88000bac5ce8)
0xffff88000bac5ca0 0xffffffffa02ace9d [zfs]dsl_dataset_promote+0xe1 (invalid)
0xffff88000bac5e00 0xffffffffa02f37e9 [zfs]zfs_ioc_promote+0x49 (0xffffc90000e28000)
0xffff88000bac5e20 0xffffffffa02f52cb [zfs]zfs_ioctl+0x125 (invalid, invalid, 0x7ffffd05fd20)
0xffff88000bac5e60 0xffffffff81108cdc vfs_ioctl+0x22 (invalid, invalid, invalid)
0xffff88000bac5ea0 0xffffffff81109238 do_vfs_ioctl+0x47b (invalid, invalid, invalid, 0x7ffffd05fd20)
0xffff88000bac5f30 0xffffffff811092d4 sys_ioctl+0x56 (invalid, invalid, 0x7ffffd05fd20)
bb_parse_opcode: no match at [kernel]system_call 0xffffffff81011c67 - 'cs'
0xffff88000bac5f80 0xffffffff81011cf2 system_call_fastpath+0x16 (invalid, invalid, invalid, invalid, invalid, invalid, 0x33, 0x10202, 0x7ffffd058378)
[0]kdb>

**Comment by sandipd** [comment]
Updated by Anand Mitra about 1 month ago

```
* Target version set to beta
```

#2
Updated by Anand Mitra about 1 month ago

```
* Target version changed from beta to GA
```

Update Log time Watch Duplicate
Update
Change properties (More)

Tracker *

Subject *

Description
Text formatting: Help
StrongItalicUnderlineDeletedInline Code Heading 1Heading 2Heading 3 Unordered listOrdered list QuoteRemove QuotePreformatted text Link to a Wiki pageImage
1. zpool create tank dev1 2. cp -r /usr/include/ /tank 3. zfs snapshot tank@snap1 4. zfs clone tank@snap1 tank/clonefs 5. zfs promote tank/clonefs tack traceback for pid 24746 0xffff88001c7a0000 24746 1265 0 0 D 0xffff88001c7a04a8 lt-zfs sp ip Function (args) 0xffff88000bac5a88 0xffffffff814368af thread_return 0xffff88000bac5b60 0xffffffff81437e5c __down_write_nested+0x93 (invalid) 0xffff88000bac5ba0 0xffffffff81437e7f __down_write+0xb 0xffff88000bac5bb0 0xffffffff81437580 down_write+0x2f (0xffff8800149e0d20) 0xffff88000bac5bd0 0xffffffffa02a37cc [zfs]dsl_dataset_make_exclusive+0x9d (invalid, invalid) 0xffff88000bac5c20 0xffffffffa02ab372 [zfs]snaplist_make+0x142 (0xffff88000674f800, invalid, invalid, invalid, 0xffff88000bac5ce8) 0xffff88000bac5ca0 0xffffffffa02ace9d [zfs]dsl_dataset_promote+0xe1 (invalid) 0xffff88000bac5e00 0xffffffffa02f37e9 [zfs]zfs_ioc_promote+0x49 (0xffffc90000e28000) 0xffff88000bac5e20 0xffffffffa02f52cb [zfs]zfs_ioctl+0x125 (invalid, invalid, 0x7ffffd05fd20) 0xffff88000bac5e60 0xffffffff81108cdc vfs_ioctl+0x22 (invalid, invalid, invalid) 0xffff88000bac5ea0 0xffffffff81109238 do_vfs_ioctl+0x47b (invalid, invalid, invalid, 0x7ffffd05fd20) 0xffff88000bac5f30 0xffffffff811092d4 sys_ioctl+0x56 (invalid, invalid, 0x7ffffd05fd20) bb_parse_opcode: no match at [kernel]system_call 0xffffffff81011c67 - 'cs' 0xffff88000bac5f80 0xffffffff81011cf2 system_call_fastpath+0x16 (invalid, invalid, invalid, invalid, invalid, invalid, 0x33, 0x10202, 0x7ffffd058378) [0]kdb>

Status *

Priority *

Assigned to

Category Add

Target version Add

StartCalendar

Due dateCalendar

Estimated time Hours

% Done
Log time

Spent time Hours

Activity

Comment
Notes
Text formatting: Help
StrongItalicUnderlineDeletedInline Code Heading 1Heading 2Heading 3 Unordered listOrdered list QuoteRemove QuotePreformatted text Link to a Wiki pageImage

Files
Optional description
Add another file (Maximum size: 10 MB)
Preview

**Comment by ganeshjagtap** [comment]
This problem is solved in new code.
only we have to mount the clone manually.
(Refer issue no : 59)
