### ISSUE TITLE
zpool replace cmd fail

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#26]
Steps

1) Create zpool with disk

[root@kqinfo cmd]# zpool/zpool create -f tank /dev/sdb

2) Replace zpool

[root@kqinfo cmd]# zpool/zpool replace -f tank /dev/sdb /dev/sdc

cannot replace /dev/sdb with /dev/sdc: no such device in pool
[root@kqinfo cmd]#

**Comment by sandipd** [comment]
Updated by Anand Mitra about 1 month ago

```
* Target version set to beta
```

#2
Updated by Anand Mitra about 1 month ago

```
* Target version changed from beta to GA
```

**Comment by mitra** [comment]
not reproduceable
