### ISSUE TITLE
Improper behavior zfs share / unshare

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#27]
zfs share / unshare showing improper behavior.
Also it is not giving error in case of wrong argument.

zfs share / unshare should show fallowing behavior:
1. zfs share should show error when try to share the already shared FS.
2. zfs unshare should show error when try to share the already shared FS.

**Comment by sandipd** [comment]
Updated by Anand Mitra about 1 month ago

```
* Target version changed from beta to GA
```

**Comment by mitra** [comment]
need to add dependency in packages to ensure that the "exportfs" command that we fire from zfs is present on the installed machine.

**Comment by mitra** [comment]
verified against solaris by Vikram. The messages saying the filesystem is already shared are output in solaris but not on linux.

This is not very critical. Lets address this post GA.

**Comment by vikramjadhav** [comment]
- Share/unshare improper behavior when sharenfs/sharesmb property off :
- zfs share should show error when try to share FS with sharenfs / sharesmb off
  Error should be like: 
      "cannot share 'FS': legacy share
      use share(1M) to share this filesystem, or set sharenfs property on"
1. zfs unshare should show error when try to unshare FS with sharenfs / sharesmb off
   Error should be like :
   " cannot unshare 'FS': legacy share
   use unshare(1M) to unshare this filesystem"
