### ISSUE TITLE
zfs destroy of snapshot after automounting deadlock happens

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#28]
1. create snapshots
2. cd poolname/.zfs/snapshot/snapname
3. zfs destroy snapname

deadlock

**Comment by sandipd** [comment]
Updated by Anand Mitra about 1 month ago

```
* Target version set to GA
```

**Comment by mitra** [comment]
fixed

[root@zfs zfs]# zfs list -t all
NAME        USED  AVAIL  REFER  MOUNTPOINT
tank        161K  5.86G    30K  /tank
tank@snap    20K      -    30K  -
[root@zfs zfs]# cd /tank/.zfs/snapshot/snap/
[root@zfs snap]# zfs destroy tank@snap
cannot unmount '/tank/.zfs/snapshot/snap': Device or resource busy
[root@zfs snap]# cd 
[root@zfs ~]# zfs destroy tank@snap
