### ISSUE TITLE
etting the mountpoint property of a zfs file system to legacy,and again setting its mountpoint umounts the file system.

### ISSUE THREAD

**Issue by mitra** [zfs-linux/zfs#3]
[root@kqinfo ZFS_kq]# zfs list
NAME USED AVAIL REFER MOUNTPOINT
tank 5.73M 1.95G 28K /mnt
tank/clone 0 1.95G 5.50M /mnt/clone
tank/fs 5.52M 1.95G 5.50M /mnt/fs
tank/fs3 20K 1.95G 20K /mnt/fs3

[root@kqinfo ZFS_kq]# mount -t zfs
tank on /mnt type zfs (rw)
tank/clone on /mnt/clone type zfs (rw)
tank/fs on /mnt/fs type zfs (rw)
tank/fs3 on /mnt/fs3 type zfs (rw)

[root@kqinfo ZFS_kq]# zfs set mountpoint=legacy tank
[root@kqinfo ZFS_kq]# mount -t zfs
[root@kqinfo ZFS_kq]# zfs list
NAME USED AVAIL REFER MOUNTPOINT
tank 5.73M 1.95G 28K legacy
tank/clone 0 1.95G 5.50M legacy
tank/fs 5.52M 1.95G 5.50M legacy
tank/fs3 20K 1.95G 20K legacy

[root@kqinfo ZFS_kq]# zfs set mountpoint=/tank tank
[root@kqinfo ZFS_kq]# mount -t zfs
[root@kqinfo ZFS_kq]# zfs mount -a

[root@kqinfo ZFS_kq]# mount -t zfs
tank on /tank type zfs (rw)
tank/clone on /tank/clone type zfs (rw)
tank/fs on /tank/fs type zfs (rw)
tank/fs3 on /tank/fs3 type zfs (rw)

**Comment by mitra** [comment]
bug has been created by Harshada

**Comment by ganeshjagtap** [comment]
You can manage ZFS file systems with legacy tools by setting the mountpoint property to legacy. Legacy file systems must be managed through the mount and umount commands and the /etc/vfstab file. ZFS does not automatically mount legacy file systems at boot time, and the ZFS mount and umount commands do not operate on datasets of this type.
