### ISSUE TITLE
startup script to initialize pool configs

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#30]
currently we need to do a zpool import each time to recreate the pools on the disk. this should be automated in a script on startup.

```
* seems like it would be ok to do this automatically
* check what is done in opensolaris so that behaviour is mirrored.
```

**Comment by sandipd** [comment]
Updated by Anand Mitra 2 months ago

```
* Target version set to beta
```

#2
Updated by Anand Mitra 2 months ago

```
* Assigned to set to Neependra Khare
```

#3
Updated by Neependra Khare about 1 month ago

```
* Assigned to changed from Neependra Khare to shrirang phansalkar
```

#4
Updated by Anand Mitra about 1 month ago

Comment
- Shrirang please confirm that the script is working on all three platforms
- Fedora 12
- Redhat 6 beta
- Ubuntu.
  #5
  Updated by Anand Mitra 14 days ago
  - Assigned to changed from shrirang phansalkar to sandip divekar

Comment

verify that this is working on all three platforms.
#6
Updated by Anand Mitra 14 days ago

```
* Assigned to changed from sandip divekar to Sachin Dhomse
```

**Comment by mitra** [comment]
fixed script has been added.
