### ISSUE TITLE
fstest failures chmod chown

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#31]
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chmod/00.t   (Wstat: 0 Tests: 58 Failed: 7)
  Failed tests:  38-39, 42-43, 46-47, 56
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chmod/01.t   (Wstat: 0 Tests: 5 Failed: 1)
  Failed test:  3
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chmod/02.t   (Wstat: 0 Tests: 5 Failed: 1)
  Failed test:  5
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chmod/07.t   (Wstat: 0 Tests: 14 Failed: 4)
  Failed tests:  7-8, 10-11
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/00.t   (Wstat: 0 Tests: 171 Failed: 28)
  Failed tests:  4, 10, 23-24, 27-28, 33, 35, 37, 69, 73
                77, 84, 88, 96, 106, 117, 130, 141, 145
                149, 153, 156-157, 160-161, 164-165
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/01.t   (Wstat: 0 Tests: 5 Failed: 1)
  Failed test:  3
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/02.t   (Wstat: 0 Tests: 5 Failed: 2)
  Failed tests:  3, 5
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/05.t   (Wstat: 0 Tests: 15 Failed: 2)
  Failed tests:  6, 10
/root/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/07.t   (Wstat: 0 Tests: 11 Failed: 4)
  Failed tests:  5-8

**Comment by sandipd** [comment]
Updated by Neependra Khare 2 months ago

```
* Assigned to changed from rohan puri to Neependra Khare
```

Comment

Fixed an issue with setattr
http://bugs.kqinfotech.com/issues/497

number of failed cases for chown are reduced.

## Test Summary Report

/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/00.t (Wstat: 0 Tests: 171 Failed: 12)
Failed tests: 84, 88, 141, 145, 149, 153, 156-157, 160-161
164-165
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/01.t (Wstat: 0 Tests: 5 Failed: 1)
Failed test: 3
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/02.t (Wstat: 0 Tests: 5 Failed: 1)
Failed test: 5
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/07.t (Wstat: 0 Tests: 11 Failed: 4)
Failed tests: 5-8
#2
Updated by Neependra Khare about 1 month ago

Comment

home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/00.t (Wstat: 0 Tests: 171 Failed: 6)
Failed tests: 84, 88, 141, 145, 149, 153

Some of the chown testcases fails on ext4 as well.

[root@zfs tmp]# prove /home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/00.t .. Failed 6/171 subtests
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/01.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/02.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/03.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/04.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/05.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/06.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/07.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/08.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/09.t .. ok
/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/10.t .. ok

## Test Summary Report

/home/kqinfo/ZFS_kq/testing/fstest/pjd-fstest-20080816/tests/chown/00.t (Wstat: 0 Tests: 171 Failed: 6)
Failed tests: 84, 88, 141, 145, 149, 153
Files=11, Tests=233, 34 wallclock secs ( 0.05 usr 0.08 sys + 3.18 cusr 3.25 csys = 6.56 CPU)
Result: FAIL
#3
Updated by Anand Mitra about 1 month ago

```
* Target version changed from beta to GA
```

Comment
- we are bug compatible with ext4. look deeper post beta.

**Comment by mitra** [comment]
closing will examine all closed bugs with tag "post GA" later.
