### ISSUE TITLE
Removing file does not free the disk space

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#32]
Description

Steps:
1) Create zpool
2) Fill the zfs till 10%
You can use following script to fill zfs to 10%
# !/bin/bash

i=0
count=`df -kh /tank | tr -s ' %' ' ' | cut -f5 -d ' '|tail -n 1`
while [ $count -le 10 ]
do
dd if=/dev/urandom of=/tank/fs$i bs=4K count=256
if test $? -ne 0
then
echo " Value i = $i"
fi
count=`df -kh /tank | tr -s ' %' ' ' | cut -f5 -d ' '|tail -n 1`
i=`expr $i + 1`
done

3) Cheak the usage

root@sachin cmd]# df -kh /tank
Filesystem Size Used Avail Use% Mounted on
tank 22G 2.2G 20G 11% /tank

4) Remove all the file on zfs and see the df -kh output.

[root@sachin cmd]# df -kh /tank
Filesystem Size Used Avail Use% Mounted on
tank 22G 507M 22G 3% /tank

Still showing used 507M

5) Unmount and remount the fs and note the df -kh

[root@sachin cmd]# df -kh /tank
Filesystem Size Used Avail Use% Mounted on
tank 22G 104K 22G 1% /tank

**Comment by sandipd** [comment]
Updated by Sachin Dhomse 2 months ago

Comment
1. Hardware Information

Type of machine   : amd64 (Virtual machine)
1. Software Information

Operating System      : Fedora 12
   Kernel version        : 2.6.31.5-127.fc12.x86_64
   ZFS Repository Number : Not trusting file /home/kqinfo/ZFS_kq/.hg/hgrc from untrusted user         root,group root
Not trusting file /home/kqinfo/ZFS_kq/.hg/hgrc from untrusted user root,   group root
changeset:   67:7f4596ec8513
tag:         tip
user:        Prasad Joshi &lt;prasad@kqinfotech.com&gt;
date:        Tue Aug 03 17:29:03 2010 +0530
summary:     Use number of blocks returned by zfs_getattr in lzfs_vnop_getattr

Linux sachin 2.6.31.5-127.fc12.x86_64 #1 SMP Sat Nov 7 21:11:14 EST 2009 x86_64 x86_64 x86_64 GNU/Linux
#2
Updated by Prasad Joshi 2 months ago

```
* Assigned to set to Prasad Joshi
```

#3
Updated by Prasad Joshi 2 months ago

```
* Assigned to changed from Prasad Joshi to Neependra Khare
```

#4
Updated by Anand Mitra 2 months ago

```
* Target version set to beta
```

#5
Updated by Anand Mitra 14 days ago

Comment

I don't think this is a genuine issue. Could you please confirm.

**Comment by mitra** [comment]
not a genuine problem.
