### ISSUE TITLE
zpool create testcases - From ZFS_kq/zfs-0.4.7/scripts/

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#33]
To do the zpool "create" testing there are some configuration given in the scripts folder (ZFS_kq/zfs-0.4.7/scripts/zpool-config).
I was able to run following tests successfully. Attaching the logs for the same.
dm0-raid0.sh
file-raid0.sh
file-raid10.sh
file-raidz2.sh
file-raidz.sh
lo-raid0.sh
lo-raid10.sh
lo-raidz2.sh
lo-raidz.sh
md0-raid10.sh
md0-raid5.sh
sda-raid0.sh

```
* Following I need to run
  hda-raid0.sh - It just a matter of having a "hd" device.
  ram0-raid0.sh - While running this test case I got following:-
  root@localhost scripts]# ./zpool-create.sh -c ram0-raid0 -v
  /home/kqinfo/ZFS_kq/zfs-0.4.7/cmd/zpool/zpool create tank /dev/ram0
  cannot create 'tank': one or more devices is less than the minimum size (64M)
```

I need to create a ram disk bigger thab 64M to run this test case.

```
* Following testcases seems to be hardware specific, which we can't ruun now.
  dragon-raid0-1x70.sh
  dragon-raid10-35x2.sh
  dragon-raidz2-7x10.sh
  dragon-raidz-7x10.sh
  promise-raid0-1x16.sh
  promise-raid10-8x2.sh
  promise-raidz2-2x8.sh
  promise-raidz-2x8.sh
  x4550-raid0-1x48.sh
  x4550-raid10-24x2.sh
  x4550-raidz2-8x6.sh
  x4550-raidz-8x6.sh
```

**Comment by sandipd** [comment]
Updated by Anand Mitra 2 months ago

```
* Due date set to 08/16/2010
* Assigned to set to Neependra Khare
* Target version set to beta
```

Comment

Could you have someone check on these.

**Comment by mitra** [comment]
to check the original logs see bug id#87 on redmine.

**Comment by mitra** [comment]
done
