### ISSUE TITLE
cifs nfs shares

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#34]

**Comment by sandipd** [comment]
Updated by Anand Mitra 2 months ago

```
* Due date set to 08/13/2010
* Assigned to set to Anand Mitra
* Target version set to beta
```

Comment

verify that the cifs/nfs export parts are in the solaris kernel and not in the base code. Once that is established we will perhaps never have cifs/nfs in linux unless a major porting effort is planed for that.
#2
Updated by Anand Mitra about 1 month ago

```
* Target version changed from beta to GA
```

**Comment by mitra** [comment]
done
