### ISSUE TITLE
aio read/write not yet implemented

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#36]
Hi,

In the inode operations vector I could see that async read/write and splice read/write are not yet implemented.

I am not sure that is the behaviour for splice read/write.

**Comment by sandipd** [comment]
Updated by Neependra Khare 2 months ago

```
* Assigned to changed from rohan puri to Neependra Khare
* Target version set to GA
```

Comment

Not targeting for beta
#2
Updated by Neependra Khare 2 months ago

```
* Status changed from New to hold
```

**Comment by mitra** [comment]
done.
