### ISSUE TITLE
i/o error injection 

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#37]
1. zpool has some option to inject errors
2. check if losetup has options to inject errors
3. systap to inject errors.

**Comment by sandipd** [comment]
Updated by Neependra Khare 2 months ago

```
* Status changed from New to Closed
```

#2
Updated by Neependra Khare 2 months ago

```
* Status changed from Closed to hold
```

Comment

Should go to features.
By mistake got closed.

**Comment by mitra** [comment]
won't do this
