### ISSUE TITLE
need to port extended attr , acl (non-trivia part) and fuid sometime later

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#38]

**Comment by sandipd** [comment]
Updated by rohan puri 7 months ago

Comment

zfs use's NFSv4 style acls , linux has no support for it need to look into that also sometime later.

Also ls and chmod are used to get and set acls in zfs need to do mapping of them also in linux or find so way out.
#2
Updated by Anand Mitra 2 months ago

```
* Target version set to GA
```

Comment

this is a major investigation is required to get this working.

**Comment by mitra** [comment]
done
