### ISSUE TITLE
Porting filebench to Linux 

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#40]
Solaris has FS bench mark tool
http://www.solarisinternals.com/wiki/index.php/FileBench

We need to get it working on Linux .

Following might be useful
http://www.cs.rice.edu/~gulati/#Tools_and_Hacks
http://sourceforge.net/projects/filebench/

**Comment by sandipd** [comment]
Updated by Neependra Khare 7 months ago

```
* File filebench-1.4.8.tar.gz added
* File libtecla-1.6.1.tar.gz added
* File filebench_install.sh added
```

#2
Updated by Anand Mitra 2 months ago

```
* Assigned to changed from Amit G to Neependra Khare
* Target version set to beta
```

Comment

Did it work ? could we use it ?
#3
Updated by Anand Mitra about 1 month ago

```
* Target version changed from beta to GA
```

**Comment by mitra** [comment]
done
