### ISSUE TITLE
Using STF for the ZFS testing

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#41]
We were exploring the option to use STF for our testing. We can't download the build package from the Solaris site and use it. So we have to download the source and compile it.

The makefile syntax vary in GNU make and Solaris make, so we have to first convert that then only we can proceed.
Even after doing that we will have to covert the the given test scripts for Liunx. It will again be lot of work.

I would suggest to refer the test scripts and create new scripts for Linux which can become part of LTP.

**Comment by sandipd** [comment]
Updated by Anand Mitra 2 months ago

```
* Assigned to set to rohan puri
* Target version set to beta
```

**Comment by mitra** [comment]
after GA
