### ISSUE TITLE
Fails- Reservation properties preserved across exports and imports

### ISSUE THREAD

**Issue by harshada** [zfs-linux/zfs#42]
Steps:
1 create a pool
2 create a file system
3 Set reservation on to it
4 Export the pool
5 Import the pool back
6 Check the reservation
It fails with what was set before export.

**Comment by nkhare** [comment]
Was not able to re-produce the problem with current code.
zfs commit : f33dc4bf93596e74dcb356f8f58a34c78321cf42

[root@f14zfs scripts]# ../cmd/zpool/zpool create npool  /dev/sda1 /dev/sdb1
[root@f14zfs scripts]# ../cmd/zpool/zpool list
NAME    SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
npool  1.98G    70K  1.98G     0%  1.00x  ONLINE  -
[root@f14zfs scripts]# ../cmd/zfs/zfs create npool/fs1
[root@f14zfs scripts]# ../cmd/zfs/zfs set reservation=1G npool/fs1
[root@f14zfs scripts]# ../cmd/zfs/zfs get reservation npool/fs1
NAME       PROPERTY     VALUE   SOURCE
npool/fs1  reservation  1G      local
[root@f14zfs scripts]# ../cmd/zpool/zpool export npool
[root@f14zfs scripts]# ../cmd/zpool/zpool list
no pools available
[root@f14zfs scripts]# ../cmd/zpool/zpool import npool
[root@f14zfs scripts]# ../cmd/zpool/zpool list
NAME    SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
npool  1.98G   192K  1.98G     0%  1.00x  ONLINE  -
[root@f14zfs scripts]# ../cmd/zfs/zfs get reservation npool/fs1
NAME       PROPERTY     VALUE   SOURCE
npool/fs1  reservation  1G      local

**Comment by ganeshjagtap** [comment]
issue solved. not able to re-produce the problem with current code.
