### ISSUE TITLE
selinux issue

### ISSUE THREAD

**Issue by rohan-puri** [zfs-linux/zfs#45]
got the zfs release, installed on RHEL 6 beta2. Using

LSI MegaRaid 9260-8i with eight hitachi 2 GB SATA disks.

The 9260-8i doesn't want to go into JBOD mode so

I set it up as eight individual RAID 0 disks, which

serve as the underlying block devices.

BTW, this box has two controllers on it, so I'm thinking

about doing a direct compare to btrfs.

I'm having some write permissions for some reason that

is probably stupid. Freshly created zpools, cd into the

mount point and get no write permissions as root:

[root@localhost tankraid]# cat /dev/null > foo.txt

bash: foo.txt: Permission denied

drwxrwxrwx.   2 root root     2 Oct 23 16:02 tankmirror

drwxrwxrwx.   2 root root     2 Oct 23 16:03 tankraid

[root@localhost /]# getfacl /tankraid

getfacl: Removing leading '/' from absolute path names
# file: tankraid
# owner: root
# group: root

user::rwx

group::rwx

other::rwx

[root@localhost mcgredo]# zpool status

  pool: tankmirror

 state: ONLINE

 scrub: none requested

config:

```
        NAME        STATE     READ WRITE CKSUM

        tankmirror  ONLINE       0     0     0

          mirror    ONLINE       0     0     0

            sda1    ONLINE       0     0     0

            sdb1    ONLINE       0     0     0
```

errors: No known data errors

  pool: tankraid

 state: ONLINE

 scrub: none requested

config:

```
        NAME        STATE     READ WRITE CKSUM

        tankraid    ONLINE       0     0     0

          raidz1    ONLINE       0     0     0

            sdc1    ONLINE       0     0     0

            sdd1    ONLINE       0     0     0

            sde1    ONLINE       0     0     0

            sdf1    ONLINE       0     0     0

            sdg1    ONLINE       0     0     0

            sdh1    ONLINE       0     0     0
```

[root@localhost /]# zfs get all tankraid

NAME      PROPERTY              VALUE                  SOURCE

tankraid  type                  filesystem             -

tankraid  creation              Sat Oct 23 16:03 2010  -

tankraid  used                  105K                   -

tankraid  available             8.89T                  -

tankraid  referenced            33.2K                  -

tankraid  compressratio         1.00x                  -

tankraid  mounted               yes                    -

tankraid  quota                 none                   default

tankraid  reservation           none                   default

tankraid  recordsize            128K                   default

tankraid  mountpoint            /tankraid              default

tankraid  sharenfs              off                    default

tankraid  checksum              on                     default

tankraid  compression           off                    default

tankraid  atime                 on                     default

tankraid  devices               on                     default

tankraid  exec                  on                     default

tankraid  setuid                on                     default

tankraid  readonly              off                    default

tankraid  zoned                 off                    default

tankraid  snapdir               hidden                 default

tankraid  aclmode               groupmask              default

tankraid  aclinherit            restricted             default

tankraid  canmount              on                     default

tankraid  shareiscsi            off                    default

tankraid  xattr                 off                    temporary

tankraid  copies                1                      default

tankraid  version               4                      -

tankraid  utf8only              off                    -

tankraid  normalization         none                   -

tankraid  casesensitivity       sensitive              -

tankraid  vscan                 off                    default

tankraid  nbmand                off                    default

tankraid  sharesmb              off                    default

tankraid  refquota              none                   default

tankraid  refreservation        none                   default

tankraid  primarycache          all                    default

tankraid  secondarycache        all                    default

tankraid  usedbysnapshots       0                      -

tankraid  usedbydataset         33.2K                  -

tankraid  usedbychildren        72.2K                  -

tankraid  usedbyrefreservation  0                      -

**Comment by ganeshjagtap** [comment]
This problem is not reproducible as per latest code.
