### ISSUE TITLE
Unable to set the device propery off 

### ISSUE THREAD

**Issue by yogita-chavan** [zfs-linux/zfs#46]
steps
1) Create zpool
2) Create file system on zpool
3) set devices property on 
[root@kqinfo kqinfo]# zfs set devices=on tank/fs

[root@kqinfo kqinfo]# zfs get devices tank/fs
NAME     PROPERTY  VALUE    SOURCE
tank/fs  devices   on       local

4) set device property off 
 [root@kqinfo kqinfo]# zfs set devices=off tank/fs

 [root@kqinfo kqinfo]# zfs get devices tank/fs
 NAME     PROPERTY  VALUE    SOURCE
 tank/fs  devices   on       temporary

**Comment by mitra** [comment]
find out the behaviour on solaris.

**Comment by deepenmehta** [comment]
Disable this property for this GA 0.5.2 version as we are not able to get the behaviour of devices=off until mknod on device file will set the major and minor version and not to 0 0.
