### ISSUE TITLE
 create pool with mirror export & import property get fail

### ISSUE THREAD

**Issue by sachin11** [zfs-linux/zfs#47]
Steps :-
1) Create pool with mirror

[root@kqinfo kqinfo]# zpool create tank -f mirror /disk.4236/a /disk.4236/b /disk.4236/c
[root@kqinfo kqinfo]# zpool list
NAME   SIZE   USED  AVAIL    CAP  HEALTH  ALTROOT
tank  59.5M  75.5K  59.4M     0%  ONLINE  -
[root@kqinfo kqinfo]# zpool status
  pool: tank
 state: ONLINE
 scrub: none requested
config:

```
    NAME              STATE     READ WRITE CKSUM
    tank              ONLINE       0     0     0
      mirror          ONLINE       0     0     0
        /disk.4236/a  ONLINE       0     0     0
        /disk.4236/b  ONLINE       0     0     0
        /disk.4236/c  ONLINE       0     0     0
```

errors: No known data errors

2) export created pool

[root@kqinfo kqinfo]# zpool export tank
[root@kqinfo kqinfo]# zpool list
no pools available
[root@kqinfo kqinfo]# zpool status
no pools available
3) import created pool
[root@kqinfo kqinfo]# zpool import tank
cannot import 'tank': no such pool available

Result :- At the time of export the zpool, it get destroy

**Comment by mitra** [comment]
works fine.
