### ISSUE TITLE
 "zfs set xattr=on" causes oops

### ISSUE THREAD

**Issue by mitra** [zfs-linux/zfs#5]
Issue raised by: Simpson, Tom Tom.Simpson@cbts.cinbell.com

Hello,

Aftet "zfs set xattr=on", on fiberchannel presented disks into a zpool, and a reboot I am seeing the following output in dmesg. (See below)

Along with this, the host hangs with any zfs/zpool commands.

Best regards,

Tom.

[   25.076245] ------------[ cut here ]------------
[   25.076623] kernel BUG at /tmp/spl-build-root-mNzPKpLq/BUILD/spl-0.4.7/module/spl/spl-debug.c:1129!
[   25.077280] invalid opcode: 0000 [#1] SMP
[   25.077870] last sysfs file: /sys/devices/system/cpu/cpu15/cache/index2/shared_cpu_map
[   25.078468] CPU 8
[   25.078804] Modules linked in: lzfs zfs(P) zcommon(P) znvpair(P) zavl(P) zlib_deflate zunicode(P) spl fbcon tileblit font bitblit softcursor ixgbe tpm_tis ioatdma vga16fb tpm vgastate tpm_bios mdio dca lp joydev parport usbhid hid usb_storage mptsas mptscsih qla2xxx mptbase scsi_transport_fc scsi_tgt scsi_transport_sas
[   25.086131] Pid: 1517, comm: zpool Tainted: P           2.6.32-24-server #39-Ubuntu N20-B6620-1
[   25.086769] RIP: 0010:[<ffffffffa017de4e>]  [<ffffffffa017de4e>] spl_debug_bug+0x8e/0xc0 [spl]
[   25.087547] RSP: 0018:ffff8805dfd39ca8  EFLAGS: 00010202
[   25.103906] RAX: 0000000000000000 RBX: 0000000000000000 RCX: ffff8805dfd39c50
[   25.103907] RDX: ffff8805dfd39c50 RSI: 0000000000000282 RDI: 0000000000000282
[   25.103908] RBP: ffff8805dfd39cd8 R08: ffff8805dfd38000 R09: 0000000000000000
[   25.103909] R10: 0000000000000002 R11: 0000000000000001 R12: 0000000000000003
[   25.103910] R13: 0000000000000001 R14: 0000000000000000 R15: 0000000000000000
[   25.103912] FS:  00007faa3d163b40(0000) GS:ffff88000c900000(0000) knlGS:0000000000000000
[   25.103913] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[   25.103914] CR2: 00007f8ad4610cfc CR3: 0000000360c67000 CR4: 00000000000006e0
[   25.103915] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   25.103916] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
[   25.103918] Process zpool (pid: 1517, threadinfo ffff8805dfd38000, task ffff8805e13ec4d0)
[   25.103918] Stack:
[   25.103919]  0000000000000000 0000000000000000 ffffffffa0186cb2 ffff88036165e800
[   25.103920] <0> 0000000000000000 ffff88035c34a000 ffff8805dfd39d48 ffffffffa025dda0
[   25.103922] <0> ffff880300000000 ffff88035e548000 0000000000000003 0000000000000001
[   25.103924] Call Trace:
[   25.103938]  [<ffffffffa025dda0>] spa_load_log_state+0x120/0x180 [zfs]
[   25.103951]  [<ffffffffa025e407>] spa_load+0x607/0xac0 [zfs]
[   25.103964]  [<ffffffffa025e968>] spa_tryimport+0xa8/0x350 [zfs]
[   25.103978]  [<ffffffffa0281729>] zfs_ioc_pool_tryimport+0x49/0x90 [zfs]
[   25.103982]  [<ffffffffa018022d>] ? vmem_alloc_debug+0x7d/0x90 [spl]
[   25.103996]  [<ffffffffa0281d2c>] zfs_ioctl+0x10c/0x1d0 [zfs]
[   25.103998]  [<ffffffff811546a2>] vfs_ioctl+0x22/0xa0
[   25.104000]  [<ffffffff81154841>] do_vfs_ioctl+0x81/0x410
[   25.104001]  [<ffffffff8155d5e3>] ? do_page_fault+0x153/0x3b0
[   25.104003]  [<ffffffff81154c51>] sys_ioctl+0x81/0xa0
[   25.104005]  [<ffffffff810131b2>] system_call_fastpath+0x16/0x1b
[   25.104007] Code: 4b 83 3d 55 c0 00 00 00 74 0a c7 05 e9 fa 00 00 01 00 00 00 31 ff e8 22 eb ff ff 89 df e8 7b fe ff ff 83 3d 34 c0 00 00 00 74 04 <0f> 0b eb fe 65 48 8b 14 25 c0 cb 00 00 b8 02 00 00 00 48 87 02
[   25.104017] RIP  [<ffffffffa017de4e>] spl_debug_bug+0x8e/0xc0 [spl]
[   25.104021]  RSP <ffff8805dfd39ca8>
[   25.104028] ---[ end trace 7cbf722edae0e80f ]---

**Comment by ganeshjagtap** [comment]
This problem is resolved.
