### ISSUE TITLE
zdb  command fails with  "-cudi"  option .

### ISSUE THREAD

**Issue by sandipd** [zfs-linux/zfs#53]
I got an error while doing following steps :
1) create pool 
2) create filesystem 
3) do some write / read operation 
4)zdb -cudi  pool/zfs
error is :-
$ zdb -cudi tank/zfs
zdb: can't open tank/zfs: Value too large for defined data type
/usr/local/sbin/zdb detected errors with: 'tank/zfs'

**Comment by ganeshjagtap** [comment]
I tried for zdb command,
cannot use '/dev/sdb1': character device required

Steps to reproduce an error:
1) $ zpool create tank sdb1
2) $ zdb -l /dev/sdb1
cannot use '/dev/sdb1': character device required

I tried to solve the problem. When I go though code in file "zfs/cmd/zdb/zdb.c"
function dump_label(), it directly return that the "character device required"

I created one character device which mapping to block device.
$ raw /dev/raw/raw1 /dev/sdb1 /dev/raw/raw1: bound to major 8, minor 17

After that I changed the code file is "zfs/cmd/zdb/zdb.c"

1788 int len = strlen(dev) + 6;
1797 (void) snprintf(path, len, "%s", "/dev/raw/raw1");

After that I got an error : cannot open '/dev/raw/raw1': Device or resource busy

In this case tank is mounted and /dev/sdb1 is indirectly mounted.

so we export the pool tank
$zpool export tank

$cmd/zdb/zdb -l /dev/sdb1

It will work but error is : "failed to read label 0"

**Comment by mitra** [comment]
- review after GA
