### ISSUE TITLE
zvol : problem while creating volume with name ore than 32 chars,

### ISSUE THREAD

**Issue by shrirang** [zfs-linux/zfs#56]
steps to generate problem

$]zpool create mypool sda1
$]zfs create -V 200M mypool/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

$] zfs list -t all | grep mypool

mypool                                                                                       200M  1.76G    20K  /mypool
mypool/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa   200M  1.95G    16K  -

$] ls /dev/mypool/
aaaaaaaaaaaaaaaaaaaaaaaa

**Comment by shrirang** [comment]
Debugged the problem vol name is persistent throughout the code.
So it seems to be problem with udev not with our zfs code.

**Comment by mitra** [comment]
the device is getting created via udev daemon. The device name seems to be a limitation of the udev interface. The name is not truncated in the zfs part of the code.
