### ISSUE TITLE
Writing with buffered IO and and reading with mmap corrupts the data.

### ISSUE THREAD

**Issue by nkhare** [zfs-linux/zfs#57]

**Comment by mitra** [comment]
The ioutility does multi-threaded buffered write / mmap read. 

The corruption is always 4k and is alligned to 4k. The corruption is that data is replaced with zeros. We had instrumented the putpage path to check if a zeroed page on the radix tree was getting flushed to the disk. However after putting that instrumentation we observed that even when the data was corrupted we did not get any calls to writepage.
