### ISSUE TITLE
After cloning snapshot, need to do zfs mount to see 'clone directory and dataset in clone'

### ISSUE THREAD

**Issue by vikramjadhav** [zfs-linux/zfs#59]
Issue : After cloning snapshot, need to do zfs mount to see dataset in clone 

Steps:
1.) List file system in pool named "tank"
     [root@kqinfo tank]# ls
      zfs  zfs1  zfs3

2.) Create dataset in /tank/zfs/ directory

  touch a
  dd if=/dev/zero of=/tank/zfs/disk bs=1M count=100

3.) Take snapshot on zfs

  zfs snapshot tank/zfs@snap01

4.) clone snapshot tank/zfs@snap01 to tank/zfs3/clone01

  zfs clone tank/zfs@snap01 tank/zfs3/clone01

5.) if we see directory #ls /tank/zfs3/
    nothing will be there

6.) 
    zfs mount -a

7.) List clone directory
    [root@kqinfo zfs]# ls /tank/zfs3/clone3/
        a  mydisk

**Comment by prashantwakchaure** [comment]
Issue is Solved and following is the diff file for same.
diff --git a/cmd/zfs/zfs_main.c b/cmd/zfs/zfs_main.c
index 38a5a9b..3116f64 100644
--- a/cmd/zfs/zfs_main.c
+++ b/cmd/zfs/zfs_main.c
@@ -653,19 +653,20 @@ zfs_do_clone(int argc, char **argv)
        ret = zfs_clone(zhp, argv[1], props);

```
    /* create the mountpoint if necessary */
```

-#ifdef HAVE_ZPL
        if (ret == 0) {
                zfs_handle_t *clone;

```
            clone = zfs_open(g_zfs, argv[1], ZFS_TYPE_DATASET);
            if (clone != NULL) {
                    if (zfs_get_type(clone) != ZFS_TYPE_VOLUME)
```
-                               if ((ret = zfs_mount(clone, NULL, 0)) == 0)
-                               if ((ret = zfs_mount(clone, NULL, 0)) == 0) {
  +#ifdef HAVE_ZPL
                                      ret = zfs_share(clone);
  +#endif /\* HAVE_ZPL */
- ```
                            }
                  zfs_close(clone);
          }
  }
  ```
  
  -#endif /\* HAVE_ZPL */
  
  ```
  zfs_close(zhp);
  nvlist_free(props);
  ```
