### ISSUE TITLE
Zfs Scrub pool not working Properly.

### ISSUE THREAD

**Issue by vikramjadhav** [zfs-linux/zfs#61]
After scrubing pool unable to get message  "scrub: scrub completed after 0h0m with 0 errors on Fri Dec  3 11:44:06 2010 "  in zpool status <poolname> 

-----------------------------------In SOLARIS:
Steps :
1.  Check Status of pool
   user@user:~$ zpool status pool01
   pool: pool01
   state: ONLINE
   scrub: none requested
   config:
         NAME             STATE     READ WRITE CKSUM
         pool01           ONLINE       0     0     0
         /home/user/d1  ONLINE       0     0     0
   errors: No known data errors
2. user@user:~$ pfexec zpool scrub pool01

3.
  user@user:~$ zpool status pool01
  pool: pool01
 state: ONLINE
 scrub: scrub completed after 0h0m with 0 errors on Fri Dec  3 11:44:06 2010
config:
        NAME             STATE     READ WRITE CKSUM
        pool01           ONLINE       0     0     0
          /home/user/d1  ONLINE       0     0     0
errors: No known data errors

------------------------------In LINUX fedora12 :

Steps:

1.
[root@kqinfo kqinfo]# zpool create pool01 /dev/sda1

2.
[root@kqinfo kqinfo]# zpool status pool01
  pool: pool01
 state: ONLINE
 scan: none requested
config:

```
NAME        STATE     READ WRITE CKSUM
pool01      ONLINE       0     0     0
  sda1      ONLINE       0     0     0
```

errors: No known data errors

3.
[root@kqinfo kqinfo]# zpool scrub pool01
[root@kqinfo kqinfo]# zpool status pool01
  pool: pool01
 state: ONLINE
 scan: scrub repaired 0 in 0h0m with 0 errors on Fri Dec  3 12:44:35 2010
config:

```
NAME        STATE     READ WRITE CKSUM
pool01      ONLINE       0     0     0
  sda1      ONLINE       0     0     0
```

errors: No known data errors

**Comment by mitra** [comment]
this used to work fine in beta. possible problem introduced during merge.

**Comment by shrirang** [comment]
The problem here is the version of ZFS code. In the older version it used to say scrub completed and in the newer version it says repaired. This is because there are some modifications in print_scan_status ( ) function which is responsible for printing the scrub status.
