### ISSUE TITLE
bugs from giovani

### ISSUE THREAD

**Issue by mitra** [zfs-linux/zfs#62]
Hi Anurag,
just some notes on ZFS, since we had to reboot the machine.

1)       ZFS was not starting back up: file /etc/init.d/zfsload was not marked as executable
2)       ZFS was  not loading back ZPOOL at starup: zfsload, start method,  si referring to zpool import –a and zfs mount –a but at that time path is not yet exported (sorted out by adding path, so /usr/local/sbin/zpool import –a and /usr/local/sbin/zfs mount –a
3)       Zfsload stop might fail if there are mounted zpools; need to umount zpools before the modprobe –r calls.
4)       Raidz2/3 pools: when creating raidz2/3 pools and issuing a zpool status the “hierarchy” is not correctly displayed: for a raidz3 you should see tank>raidz3-0>Disks while you see tank>-0>Disks so it is impossibile tounderstand whther is a z1,z2 or z3 pool (the raidzX info is not printed out or wrongly trimmed)
5)       Raidz3 performance: here I think there is room for improvements. A raidz3 with 14 disks performs between 800 and 1000 Mb/s (turning compression and dedup off) even when writing small amounts of data (i.e. 1Gb). It seems memory caching write back is not used in this case; cpu usage is around 50% (sys) which is similar to Solaris. Honestly I do not remember for sure solaris performance in this config, but if my memory does not fail it was between 1400 and 1700 MB/s (15/20 % les performance than stripe)

I spoke this morning with some colleagues: there might be problems (they are checking the kernel patches) in having all the infiniband stuff to work fine on Fedora 14; if so, would it be an issue for you and your tests to roll back to Centos 5.5  or there are kernel issues ?

**Comment by nkhare** [comment]
1 to 4 already fixed and committed.
