### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nkhare** [zfs-linux/zfs#66]
It looks we are having some memory leak after putting cv_broadcast changes:
commit id: 80ee0ecf3ab16c76eab14b3bfa718409dbe6a563
1. Configure spl with  "--enable-debug --enable-debug-kmem-tracking" option and compile it
2. Load the spl, zfs, lzfs modules
3. Create and mount the pool
4. Run ioutility for some time
5. Un-mount the pool
6. Unload the modules

It gives following:-
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885055] address          size  data             func:line
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885196] ffff880027bad390 13    &rl->r_wr_cv     __cv_init:61
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885205] ffff880204d83000 208   103a01ff08dd01ff zfs_range_lock:455
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885212] ffff88008daa2460 13    &rl->r_wr_cv     __cv_init:61
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885221] ffff8801972a7100 208   002a01ff00000000 zfs_range_split:253
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885230] ffff8801972a7700 208   002a01ff00000000 zfs_range_proxify:224
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885239] ffff88020acd2e00 208   00cd02ff086802ff zfs_range_proxify:224
Dec 11 13:27:42 fedora-14-47 kernel: [68519.885249] ffff8801910ee700 208   f03801ff08c202ff zfs_range_lock:455

**Comment by mitra** [comment]
all memory leaks fixed
