### ISSUE TITLE
 ls -l on a snapshot directory gives following result: ls: f1: Invalid argument 

### ISSUE THREAD

**Issue by ganeshjagtap** [zfs-linux/zfs#71]
ls -l on a snapshot directory gives following result:
root@anurag-laptop:/mypool/.zfs/snapshot/snap1# ls -l
ls: f1: Invalid argument
total 1
-rw-r--r-- 1 root root 0 2010-12-20 21:38 f1
root@anurag-laptop:/mypool/.zfs/snapshot/snap1# 

strace shows following:

open(".", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fcntl(3, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
getdents(3, /\* 3 entries */, 32768)     = 72
lstat("f1", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
lgetxattr("f1", "security.selinux", 0x26142a0, 255) = -1 EINVAL (Invalid argument)
write(2, "ls: ", 4ls: )                     = 4
write(2, "f1", 2f1)                       = 2
open("/usr/share/locale/en_IN/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_IN/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, ": Invalid argument", 18: Invalid argument)      = 18
write(2, "\n", 1
)                       = 1

**Comment by mitra** [comment]
I believe that Neependra's fix for the xattr should fix this.

Ganesh please verify

**Comment by ganeshjagtap** [comment]
Problem solved.
