### ISSUE TITLE
IO utility failed with mmap

### ISSUE THREAD

**Issue by tushk2** [zfs-linux/zfs#73]
steps to reproduce :
1. compile the code with --enable-debug --enable-debug-kmem-tracking
2. run the file run_tests.sh

see dmesg for errors 

[ 3954.931714] BUG: sleeping function called from invalid context at include/linux/kernel.h:170
[ 3954.931718] in_atomic(): 1, irqs_disabled(): 0, pid: 1921, name: wrv.fs
[ 3954.931721] Pid: 1921, comm: wrv.fs Tainted: P            2.6.35.6-48.fc14.x86_64 #1
[ 3954.931723] Call Trace:
[ 3954.931729]  [<ffffffff8103d12b>] __might_sleep+0xeb/0xf0
[ 3954.931734]  [<ffffffffa012fb55>] might_fault+0x1c/0x23 [lzfs]
[ 3954.931737]  [<ffffffffa01315b4>] lzfs_vnop_write+0x180/0x352 [lzfs]
[ 3954.931741]  [<ffffffff81117004>] vfs_write+0xac/0x100
[ 3954.931743]  [<ffffffff8111720d>] sys_write+0x4a/0x6e
[ 3954.931746]  [<ffffffff81009cf2>] system_call_fastpath+0x16/0x1b

**Comment by mitra** [comment]
not reproducable.

**Comment by mitra** [comment]
prasad's fix worked.
