### ISSUE TITLE
nfs snapshot access panics

### ISSUE THREAD

**Issue by mitra** [zfs-linux/zfs#74]
PID: 6199   TASK: ffff880079fef4a0  CPU: 0   COMMAND: "nfsd"
 #0 [ffff88007b2e18f0] machine_kexec at ffffffff8103695b
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86/kernel/machine_kexec_64.c: 336
 #1 [ffff88007b2e1950] crash_kexec at ffffffff810b8fc8
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/kernel/kexec.c: 1083
 #2 [ffff88007b2e1a20] oops_end at ffffffff814cbf80
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86/kernel/dumpstack.c: 248
 #3 [ffff88007b2e1a50] no_context at ffffffff8104651b
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86/mm/fault.c: 693
 #4 [ffff88007b2e1aa0] __bad_area_nosemaphore at ffffffff810467a5
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86/mm/fault.c: 759
 #5 [ffff88007b2e1af0] bad_area_nosemaphore at ffffffff81046873
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86/mm/fault.c: 767
 #6 [ffff88007b2e1b00] do_page_fault at ffffffff814cda08
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86/mm/fault.c: 1071
 #7 [ffff88007b2e1b50] page_fault at ffffffff814cb2f5
   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86_64/kernel/entry.S
   [exception RIP: zfs_fid+52]
   RIP: ffffffffa04acda4  RSP: ffff88007b2e1c00  RFLAGS: 00010286
   RAX: 000000000000000e  RBX: ffff88003751c154  RCX: 0000000000000000
   RDX: ffffffffa04c1440  RSI: 0000000000000002  RDI: ffff880073ca7540
   RBP: ffff88007b2e1c30   R8: ffff880079e00000   R9: 000000000000005f
   R10: ffff880037decc60  R11: 0000000000000000  R12: ffff88003751c154
   R13: ffff880075c1aa40  R14: 0000000000000004  R15: 0000000000000000
   ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #8 [ffff88007b2e1c38] lzfs_encode_fh at ffffffffa053fe07
 #9 [ffff88007b2e1c98] exportfs_encode_fh at ffffffffa02e1028
#10 [ffff88007b2e1cc8] _fh_update at ffffffffa032053d
#11 [ffff88007b2e1cf8] fh_compose at ffffffffa032118c
#12 [ffff88007b2e1d58] nfsd_lookup at ffffffffa0324013
#13 [ffff88007b2e1d98] nfsd3_proc_lookup at ffffffffa032c612
#14 [ffff88007b2e1dd8] nfsd_dispatch at ffffffffa031d43e
#15 [ffff88007b2e1e18] svc_process_common at ffffffffa029b544
#16 [ffff88007b2e1e98] svc_process at ffffffffa029bb50
#17 [ffff88007b2e1eb8] nfsd at ffffffffa031db62
#18 [ffff88007b2e1ee8] kthread at ffffffff810919d6

   /usr/src/debug/kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/kernel/kthread.c: 78
#19 [ffff88007b2e1f48] kernel_thread at ffffffff810141ca

   /usr/src/debug////////kernel-2.6.32-71.7.1.el6/linux-2.6.32-71.7.1.el6.x86_64/arch/x86/kernel/entry_64.S: 1213

**Comment by nkhare** [comment]
It happens when we try to access the .zfs directory via NFS.  This was because there is not znode is associated with the vnode for .zfs.  

For now we are not supporting the access of  zfs  over NFS. If someone tries to access it then it will give "Remote I/O error" error.

**Comment by mitra** [comment]
There is an interesting problem here which has implications beyond the this panic.

Important background. The behaviour of NFS in opensolaris as well as linux is that it will export files only within the same filesystem. If there is an other filesystem mount within the namespace of the exported filesystem the mounted filesystem cannot be traversed over NFS.  The implication of this is say you have a filesystem tank and child filesystem tank/fs mounted at the regular place you would expect them to be. Now if you export /tank you can only view files/directories that belong to tank/ everything beyond the /tank/fs will not be visible.

With this background what is surprising is that on opensolaris you can view the .zfs and snapshots within that without an explicit mount. There is code in opensolaris to explicitly clear the VFS_ROOT flag in the root of the mounted snapshot and to fake the vfsp so that nfs is fooled into believing it is the same filesystem.

We haven't done this on the linux port yet and the implication of this is that the snapshot will not be accessible. The panic above happens because the snapshot directories in .zfs/snapshots are virtual and are numbered from the top end of the inode number space. The existing code cannot convert these hypothetical directories into file handles correctly. We did not bother fixing this now since vfs fudging has to be investigated and we are sure that the same behaviour can be faked in the linux. As a result of all this snapshots won't be accessible over nfs.

**Comment by maxximino** [comment]
using:
mount -o bind /zfsmountpoint/.zfs/snapshot/snapname  /zfsmountpoint/someotherdir
the snapshot is accessibile also through nfs
