### ISSUE TITLE
Setting ZFS property do not update the output of mount command.

### ISSUE THREAD

**Issue by prasad-joshi** [zfs-linux/zfs#75]
In fact the /etc/mtab is not updated with every change in property

root@prasad-laptop:/tank# zfs set readonly=on tank

root@prasad-laptop:/tank# mount -t zfs
tank on /tank type zfs (rw)

root@prasad-laptop:/tank# echo "Test DATA" >> afile 
bash: afile: Read-only file system

The mount command should show the file system is mounted as ro, but instead it displays as file system is mount as rw.

This same behavior is observed with other properties like exec, devices, atime etc.

**Comment by deepenmehta** [comment]
Fixed....

mount would just shows rw or ro options property of FS and not other property as
rw and ro is basic thing related to FS. In able to view other properties user must
execute 'zfs get' command.
