### ISSUE TITLE
Core dumped while rollbacking snapshot.

### ISSUE THREAD

**Issue by vikramjadhav** [zfs-linux/zfs#77]
Core dumped while rollbacking snapshot.
Steps:
# zpool create tank sda1
# zfs create tank/zfs
# zfs create tank/zfs/fs1
# zfs create tank/zfs/fs2
# zfs create tank/zfs/fs3
# /usr/local/sbin/zfs snapshot -r tank/zfs@snap\
# /usr/local/sbin/zfs snapshot tank/zfs@snap2
# /usr/local/sbin/zfs snapshot tank/zfs@snap3
# /usr/local/sbin/zfs rollback -r tank/zfs@snap

internal error: Unknown error 524
Aborted (core dumped)

**Comment by mitra** [comment]
need to remove have zpl from zfs_ioc_rollback
