### ISSUE TITLE
SPL Pannic while unloading module.

### ISSUE THREAD

**Issue by vikramjadhav** [zfs-linux/zfs#80]
SPL Pannic while unloading module.
This issue regarding snapshot :

Follow the Steps:
1.# modprobe lzfs
2.# zpool create tank /dev/sda1
3.# zfs create tank/zfs
4. #zfs create tank/zfs/fs1
5. #zfs create tank/zfs/fs2
6. #zfs create tank/zfs/fs3
7. #zfs snapshot -r tank/zfs@snap
8. #cd /tank/zfs/.zfs/snapshot/snap/
9. Come out of tank directory ( cd /home/kqinfo/zfs_kq/)
10. #zpool destroy tank
11. #modprobe -r lzfs
Message from syslogd@localhost at Dec 29 12:38:12 ...
 kernel:[  633.419694] SPLError: 2242:0:(spl-kmem.c:1489:spl_kmem_cache_destroy()) VERIFY3(skc->skc_slab_alloc == 0) failed (1 == 0)

Message from syslogd@localhost at Dec 29 12:38:12 ...
 kernel:[  633.419699] SPLError: 2242:0:(spl-kmem.c:1489:spl_kmem_cache_destroy()) SPL PANIC

This issue working fine when we not traverse .zfs/snapshot directory ( except step 8 and 9 )

**Comment by mitra** [comment]
fixed. we were unnecessarily setting atime update on snapshot filesystem. This was attempting to write to the snapshot which was failing.
