### ISSUE TITLE
spl panic  when unmounting file system

### ISSUE THREAD

**Issue by tushk2** [zfs-linux/zfs#84]
<pre><code>
[root@fedora-14-230 zpool]# zfs umount -a

Message from syslogd@fedora-14-230 at Jan  5 20:00:15 ...
 kernel:[ 1998.398539] SPLError: 31392:0:(spl-vnode.c:900:vn_rele_async()) ASSERTION(vp->v_count > 0) failed

Message from syslogd@fedora-14-230 at Jan  5 20:00:15 ...
 kernel:[ 1998.398544] SPLError: 31392:0:(spl-vnode.c:900:vn_rele_async()) SPL PANIC

When we are doing big cache I/O and unmounting the file system then we get the following logs

[kqinfo@fedora-14-230 ~]$ dmesg 
[ 1911.344974] EXT3-fs: barriers not enabled
[ 1911.366897] kjournald starting.  Commit interval 5 seconds
[ 1911.380430] EXT3-fs (sde1): using internal journal
[ 1911.380449] EXT3-fs (sde1): mounted filesystem with ordered data mode
[ 1998.398539] SPLError: 31392:0:(spl-vnode.c:900:vn_rele_async()) ASSERTION(vp->v_count > 0) failed
[ 1998.398544] SPLError: 31392:0:(spl-vnode.c:900:vn_rele_async()) SPL PANIC
[ 1998.398546] SPL: Showing stack for process 31392
[ 1998.398549] Pid: 31392, comm: zfs Tainted: P            2.6.35.6-48.fc14.x86_64 #1
[ 1998.398550] Call Trace:
[ 1998.398563]  [<ffffffffa034f6a5>] spl_debug_dumpstack+0x30/0x32 [spl]
[ 1998.398568]  [<ffffffffa035082f>] spl_debug_bug+0x88/0xcd [spl]
[ 1998.398575]  [<ffffffffa035a7c8>] vn_rele_async+0x67/0xff [spl]
[ 1998.398618]  [<ffffffffa0470c5a>] zfs_get_done+0x59/0x85 [zfs]
[ 1998.398644]  [<ffffffffa0472dd0>] zfs_get_data+0x3e7/0x3f9 [zfs]
[ 1998.398670]  [<ffffffffa0479965>] zil_commit+0x4e6/0x858 [zfs]
[ 1998.398674]  [<ffffffff8103c040>] ? need_resched+0x23/0x2d
[ 1998.398676]  [<ffffffff8103c058>] ? should_resched+0xe/0x2e
[ 1998.398702]  [<ffffffffa047a572>] zil_close+0x16/0x87 [zfs]
[ 1998.398727]  [<ffffffffa046c2b9>] zfs_umount+0x51/0x274 [zfs]
[ 1998.398731]  [<ffffffffa026057d>] lzfs_put_super+0x6f/0xd8 [lzfs]
[ 1998.398734]  [<ffffffff8111863c>] generic_shutdown_super+0x5b/0xdc
[ 1998.398737]  [<ffffffff81118712>] kill_anon_super+0x16/0x4f
[ 1998.398739]  [<ffffffffa0260070>] lzfs_kill_sb+0x70/0xb8 [lzfs]
[ 1998.398742]  [<ffffffff81118943>] deactivate_locked_super+0x26/0x46
[ 1998.398744]  [<ffffffff81119407>] deactivate_super+0x3a/0x3e
[ 1998.398747]  [<ffffffff8112cd64>] mntput_no_expire+0x78/0xa4
[ 1998.398749]  [<ffffffff8112d8d1>] sys_umount+0x2d5/0x307
[ 1998.398751]  [<ffffffff81009cf2>] system_call_fastpath+0x16/0x1b
[ 1998.398846] SPL: Dumping log to /tmp/spl-log.1294237815.31392
[kqinfo@fedora-14-230 ~]$ 
</code>
</pre>

**Comment by mitra** [comment]
could not reproduce this problem.
